// ==========================================
// ICAS 數學題庫 - 100題
// ==========================================
const mathQuestions = [
    // 基礎算術 (20題)
    {q:"24 ÷ 6 = ?",o:["3","4","5","6"],a:1,d:"easy",e:"24 ÷ 6 = 4。可以想像將24顆蘋果分給6個人，每人得4顆。"},
    {q:"一本書原價 $80，打75折後售價是多少？",o:["$55","$60","$65","$70"],a:1,d:"easy",e:"75折 = 原價 × 0.75。$80 × 0.75 = $60。"},
    {q:"數列 2, 5, 8, 11, 14, ... 的下一項是？",o:["15","16","17","18"],a:2,d:"easy",e:"這是等差數列，公差為3。14 + 3 = 17。"},
    {q:"30名學生中18名是女生，女生佔多少百分比？",o:["50%","55%","60%","65%"],a:2,d:"easy",e:"18 ÷ 30 × 100% = 60%。"},
    {q:"3/4 + 1/2 = ?",o:["1/4","4/6","1 1/4","2"],a:2,d:"easy",e:"1/2 = 2/4，所以 3/4 + 2/4 = 5/4 = 1 1/4。"},
    {q:"0.75 = ?",o:["1/2","2/3","3/4","4/5"],a:2,d:"easy",e:"0.75 = 75/100 = 3/4。"},
    {q:"12米長的繩用了1/3，還剩多少米？",o:["4米","6米","8米","9米"],a:2,d:"easy",e:"用了 12 × 1/3 = 4米，還剩 12 - 4 = 8米。"},
    {q:"15的20%是多少？",o:["2","3","4","5"],a:1,d:"easy",e:"15 × 0.20 = 3。"},
    {q:"3, 7, 1, 9, 5 的中位數是？",o:["3","5","7","9"],a:1,d:"easy",e:"排序後：1, 3, 5, 7, 9。中位數是中間的5。"},
    {q:"5x = 35，x = ?",o:["5","6","7","8"],a:2,d:"easy",e:"x = 35 ÷ 5 = 7。"},
    {q:"1/5 + 2/5 = ?",o:["3/10","2/5","3/5","1"],a:2,d:"easy",e:"同分母分數相加，分子相加：1/5 + 2/5 = 3/5。"},
    {q:"哪個數字最大？",o:["0.8","0.75","0.85","0.7"],a:2,d:"easy",e:"0.85 > 0.8 > 0.75 > 0.7。"},
    {q:"36的因數有幾個？",o:["6","7","8","9"],a:2,d:"medium",e:"36的因數：1, 2, 3, 4, 6, 9, 12, 18, 36。共9個。"},
    {q:"2³ = ?",o:["6","8","9","12"],a:1,d:"easy",e:"2³ = 2 × 2 × 2 = 8。"},
    {q:"1公里 = 多少米？",o:["10","100","1000","10000"],a:2,d:"easy",e:"1公里 = 1000米。"},
    {q:"哪個是質數？",o:["9","15","17","21"],a:2,d:"medium",e:"17只能被1和17整除，是質數。9=3×3，15=3×5，21=3×7。"},
    {q:"24和36的最大公因數是？",o:["6","12","18","24"],a:1,d:"medium",e:"24=2³×3，36=2²×3²。GCD = 2²×3 = 12。"},
    {q:"3.45 + 2.67 = ?",o:["5.02","5.12","6.02","6.12"],a:1,d:"easy",e:"3.45 + 2.67 = 6.12。小數點對齊相加。"},
    {q:"1000克 = 多少公斤？",o:["0.1","1","10","100"],a:1,d:"easy",e:"1000克 = 1公斤。"},
    {q:"如果 4x = 28，x = ?",o:["5","6","7","8"],a:2,d:"easy",e:"x = 28 ÷ 4 = 7。"},

    // 代數 (20題)
    {q:"3x + 5 = 20，x = ?",o:["3","4","5","6"],a:2,d:"medium",e:"3x = 20 - 5 = 15，x = 15 ÷ 3 = 5。"},
    {q:"化簡：2(x + 3) + 3(x - 1)",o:["5x + 3","5x + 5","6x + 3","6x + 5"],a:0,d:"medium",e:"展開：2x + 6 + 3x - 3 = 5x + 3。"},
    {q:"y = 2x + 1，當 x = 4，y = ?",o:["7","8","9","10"],a:2,d:"easy",e:"y = 2(4) + 1 = 8 + 1 = 9。"},
    {q:"解方程：2(x - 3) = 10",o:["5","6","7","8"],a:3,d:"medium",e:"x - 3 = 5，所以 x = 8。"},
    {q:"a + b = 10，a - b = 4，求 a",o:["5","6","7","8"],a:2,d:"medium",e:"兩式相加：2a = 14，a = 7。"},
    {q:"因式分解：x² - 9",o:["(x-3)²","(x+3)²","(x+3)(x-3)","(x+9)(x-1)"],a:2,d:"medium",e:"平方差公式：a² - b² = (a+b)(a-b)。所以 x² - 9 = (x+3)(x-3)。"},
    {q:"3x - 7 > 5，哪個正確？",o:["x > 2","x > 3","x > 4","x > 5"],a:2,d:"medium",e:"3x > 12，x > 4。"},
    {q:"數列 1, 4, 9, 16, 25, ?",o:["30","36","42","49"],a:1,d:"medium",e:"平方數列：1², 2², 3², 4², 5², 6² = 36。"},
    {q:"x² = 64，x = ?",o:["8","-8","8或-8","16"],a:2,d:"medium",e:"8² = 64，(-8)² = 64，所以 x = ±8。"},
    {q:"化簡：(x²)³",o:["x⁵","x⁶","x⁸","x⁹"],a:1,d:"medium",e:"指數相乘：(a^m)^n = a^(mn)。2×3=6，所以是x⁶。"},
    {q:"2x + 3y = 12，當 x = 3，y = ?",o:["1","2","3","4"],a:1,d:"medium",e:"2(3) + 3y = 12，6 + 3y = 12，3y = 6，y = 2。"},
    {q:"哪個是線性方程？",o:["y = x²","y = 2x + 1","y = 1/x","y = x³"],a:1,d:"easy",e:"y = 2x + 1 是線性方程（一次方程），圖像是直線。"},
    {q:"如果 x/4 = 3，x = ?",o:["7","10","12","16"],a:2,d:"easy",e:"x = 3 × 4 = 12。"},
    {q:"化簡：3a + 2b - a + 4b",o:["2a + 6b","2a + 2b","4a + 6b","3a + 4b"],a:0,d:"easy",e:"同類項相加：3a - a = 2a，2b + 4b = 6b。答案是 2a + 6b。"},
    {q:"(x + 2)² = ?",o:["x² + 4","x² + 2x + 4","x² + 4x + 4","x² + 4x + 2"],a:2,d:"medium",e:"(a+b)² = a² + 2ab + b²。所以 (x+2)² = x² + 4x + 4。"},
    {q:"解方程組：x + y = 8，x - y = 2",o:["x=5,y=3","x=4,y=4","x=6,y=2","x=3,y=5"],a:0,d:"medium",e:"相加得 2x = 10，x = 5。代入得 y = 3。"},
    {q:"如果 2x - 5 = 3x + 1，x = ?",o:["6","-6","4","-4"],a:1,d:"medium",e:"移項：-5 - 1 = 3x - 2x，-6 = x。"},
    {q:"x³ × x² = ?",o:["x⁵","x⁶","x⁸","x⁹"],a:0,d:"medium",e:"同底數相乘，指數相加：3 + 2 = 5。所以是 x⁵。"},
    {q:"哪個是二次方程？",o:["y = x + 1","y = x² + 1","y = 1/x","y = 2x"],a:1,d:"easy",e:"y = x² + 1 是二次方程（最高次數為2）。"},
    {q:"如果 5(x - 2) = 20，x = ?",o:["4","5","6","8"],a:2,d:"medium",e:"x - 2 = 4，所以 x = 6。"},

    // 幾何 (20題)
    {q:"長方形長8cm，闊5cm，面積是多少？",o:["13cm²","26cm²","40cm²","45cm²"],a:2,d:"easy",e:"面積 = 長 × 闊 = 8 × 5 = 40cm²。"},
    {q:"三角形兩角60°和70°，第三角是多少？",o:["40°","50°","60°","70°"],a:1,d:"easy",e:"三角形內角和180°。180 - 60 - 70 = 50°。"},
    {q:"圓直徑10cm，圓周約是多少？(π≈3.14)",o:["15.7cm","31.4cm","62.8cm","78.5cm"],a:1,d:"easy",e:"圓周 = π × 直徑 = 3.14 × 10 = 31.4cm。"},
    {q:"正方形周界36cm，面積是多少？",o:["36cm²","72cm²","81cm²","144cm²"],a:2,d:"medium",e:"邊長 = 36 ÷ 4 = 9cm。面積 = 9² = 81cm²。"},
    {q:"直角三角形兩直角邊6cm和8cm，斜邊是多少？",o:["10cm","12cm","14cm","16cm"],a:0,d:"medium",e:"畢氏定理：c² = 6² + 8² = 36 + 64 = 100，c = 10cm。"},
    {q:"3:45時，時針和分針的夾角是多少？",o:["90°","120°","157.5°","180°"],a:2,d:"hard",e:"分針270°，時針112.5°。夾角 = 270 - 112.5 = 157.5°。"},
    {q:"立方體體積64cm³，表面積是多少？",o:["64cm²","72cm²","96cm²","128cm²"],a:2,d:"medium",e:"邊長 = ∛64 = 4cm。表面積 = 6 × 4² = 96cm²。"},
    {q:"平行四邊形底12cm，高5cm，面積是多少？",o:["30cm²","34cm²","60cm²","68cm²"],a:2,d:"easy",e:"面積 = 底 × 高 = 12 × 5 = 60cm²。"},
    {q:"圓柱半徑3cm，高10cm，體積是多少？(π≈3.14)",o:["90cm³","180cm³","282.6cm³","300cm³"],a:2,d:"medium",e:"體積 = πr²h = 3.14 × 9 × 10 = 282.6cm³。"},
    {q:"兩個相似三角形邊長比2:3，小三角形面積16cm²，大三角形面積是多少？",o:["24cm²","32cm²","36cm²","48cm²"],a:2,d:"hard",e:"面積比 = 邊長比² = (3/2)² = 9/4。大面積 = 16 × 9/4 = 36cm²。"},
    {q:"長方體長5cm、闊4cm、高3cm，體積是多少？",o:["12cm³","27cm³","60cm³","120cm³"],a:2,d:"easy",e:"體積 = 長 × 闊 × 高 = 5 × 4 × 3 = 60cm³。"},
    {q:"等邊三角形周長18cm，邊長是多少？",o:["4cm","5cm","6cm","9cm"],a:2,d:"easy",e:"等邊三角形三邊相等。18 ÷ 3 = 6cm。"},
    {q:"圓的面積公式是？",o:["πr","πr²","2πr","2πr²"],a:1,d:"easy",e:"圓面積 = πr²。"},
    {q:"正五邊形有幾條對角線？",o:["3","4","5","6"],a:2,d:"medium",e:"n邊形對角線數 = n(n-3)/2。5(5-3)/2 = 5條。"},
    {q:"直角三角形一銳角35°，另一銳角是多少？",o:["45°","55°","65°","75°"],a:1,d:"easy",e:"90 - 35 = 55°。"},
    {q:"梯形上底4cm、下底6cm、高5cm，面積是多少？",o:["20cm²","25cm²","50cm²","100cm²"],a:1,d:"medium",e:"面積 = (上底+下底)×高÷2 = (4+6)×5÷2 = 25cm²。"},
    {q:"圓的半徑增加一倍，面積增加多少倍？",o:["2倍","3倍","4倍","8倍"],a:2,d:"medium",e:"面積與半徑平方成正比。2² = 4，所以增加4倍。"},
    {q:"三角形底10cm，面積30cm²，高是多少？",o:["3cm","5cm","6cm","12cm"],a:2,d:"medium",e:"面積 = 底×高÷2，所以高 = 30×2÷10 = 6cm。"},
    {q:"長方形和平行四邊形同底同高，哪個面積大？",o:["長方形","平行四邊形","一樣大","無法比較"],a:2,d:"medium",e:"兩者面積都等於底×高，所以一樣大。"},
    {q:"正六邊形有幾條邊？",o:["4","5","6","8"],a:2,d:"easy",e:"正六邊形有6條邊。"},

    // 數據分析 (20題)
    {q:"數據5, 7, 8, 10, 10的平均數是多少？",o:["7","8","8.5","9"],a:1,d:"easy",e:"(5+7+8+10+10)÷5 = 40÷5 = 8。"},
    {q:"擲骰子擲出偶數的機率是多少？",o:["1/6","1/3","1/2","2/3"],a:2,d:"easy",e:"偶數有2,4,6共3個。機率 = 3/6 = 1/2。"},
    {q:"數據2, 3, 3, 5, 7, 7, 7, 8的眾數是多少？",o:["3","5","7","8"],a:2,d:"easy",e:"7出現3次，次數最多，所以眾數是7。"},
    {q:"袋中有3個紅球和5個藍球，抽到紅球的機率是多少？",o:["3/8","5/8","3/5","5/3"],a:0,d:"easy",e:"總共8個球，紅球3個。機率 = 3/8。"},
    {q:"20名學生平均分75分，如果總分增加40分，新平均分是多少？",o:["75","77","80","85"],a:1,d:"medium",e:"原總分 = 20×75 = 1500。新總分 = 1540。新平均 = 1540÷20 = 77。"},
    {q:"擲兩個骰子，點數和為7的機率是多少？",o:["1/6","1/9","1/12","6/36"],a:0,d:"medium",e:"和為7的組合有6種：(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)。機率 = 6/36 = 1/6。"},
    {q:"數據範圍是20，最小值15，最大值是多少？",o:["25","30","35","40"],a:2,d:"easy",e:"範圍 = 最大值 - 最小值。最大值 = 15 + 20 = 35。"},
    {q:"200名學生中60%是女生，男生有多少人？",o:["60","70","80","90"],a:2,d:"easy",e:"女生 = 200×60% = 120人。男生 = 200 - 120 = 80人。"},
    {q:"圓形統計圖中某類別佔25%，圓心角是多少度？",o:["45°","60°","90°","120°"],a:2,d:"medium",e:"360° × 25% = 360° × 0.25 = 90°。"},
    {q:"30%得A，40%得B，20%得C，其餘得D。200人中得D的有多少人？",o:["10","20","30","40"],a:1,d:"medium",e:"D的百分比 = 100% - 90% = 10%。人數 = 200×10% = 20人。"},
    {q:"數據3, 5, 7, 9, 11的範圍是多少？",o:["5","7","8","11"],a:2,d:"easy",e:"範圍 = 最大值 - 最小值 = 11 - 3 = 8。"},
    {q:"平均數是50，其中4個數是45, 50, 55, 60，第5個數是多少？",o:["40","45","50","55"],a:0,d:"medium",e:"5個數總和 = 50×5 = 250。已知4個數和 = 210。第5個數 = 250 - 210 = 40。"},
    {q:"拋硬幣3次，3次都是正面的機率是多少？",o:["1/3","1/6","1/8","1/9"],a:2,d:"medium",e:"每次正面機率1/2。3次正面 = (1/2)³ = 1/8。"},
    {q:"數據1, 2, 3, 4, 100的中位數是多少？",o:["2","3","4","50.5"],a:1,d:"easy",e:"排序後中間的數是3。注意：中位數不受極端值影響。"},
    {q:"班上有12名男生和18名女生，隨機選一人，選到女生的機率是多少？",o:["1/2","2/3","3/5","3/2"],a:2,d:"easy",e:"總共30人。女生18人。機率 = 18/30 = 3/5。"},
    {q:"數據的平均數是20，如果每個數加5，新平均數是多少？",o:["20","22","25","30"],a:2,d:"medium",e:"每個數加5，平均數也加5。新平均 = 20 + 5 = 25。"},
    {q:"從1到100隨機選一個數，選到平方數的機率是多少？",o:["1/10","1/20","1/25","1/100"],a:0,d:"hard",e:"1-100的平方數：1,4,9,16,25,36,49,64,81,100共10個。機率 = 10/100 = 1/10。"},
    {q:"數據的眾數是5，這表示什麼？",o:["5是最大數","5是最小數","5出現次數最多","5是中間數"],a:2,d:"easy",e:"眾數就是出現次數最多的數。"},
    {q:"一組數據的標準差越大，表示什麼？",o:["數據越集中","數據越分散","平均數越大","中位數越大"],a:1,d:"medium",e:"標準差衡量數據的離散程度。標準差越大，數據越分散。"},
    {q:"擲兩個骰子，點數積是12的機率是多少？",o:["1/9","1/12","4/36","1/6"],a:2,d:"hard",e:"積為12的組合：(2,6),(3,4),(4,3),(6,2)共4種。機率 = 4/36 = 1/9。"},

    // 邏輯與應用題 (20題)
    {q:"今天是星期二，100天後是星期幾？",o:["星期一","星期二","星期三","星期四"],a:3,d:"medium",e:"100 ÷ 7 = 14餘2。星期二 + 2天 = 星期四。"},
    {q:"數列2, 6, 12, 20, 30, ?",o:["36","40","42","48"],a:2,d:"medium",e:"規律：1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42。"},
    {q:"A > B且B > C，以下哪個正確？",o:["A < C","A = C","A > C","無法確定"],a:2,d:"easy",e:"由傳遞性，A > B > C，所以A > C。"},
    {q:"書架有5本不同的書，有幾種排列方式？",o:["25","120","125","3125"],a:1,d:"medium",e:"5! = 5×4×3×2×1 = 120種。"},
    {q:"6個工人8天完成工作，12個工人需要幾天？",o:["2天","4天","6天","16天"],a:1,d:"medium",e:"總工作量 = 6×8 = 48人天。12人需要 48÷12 = 4天。"},
    {q:"水池，甲管6小時注滿，乙管3小時注滿，兩管一起開需幾小時？",o:["2小時","3小時","4小時","9小時"],a:0,d:"hard",e:"甲每小時注1/6，乙每小時注1/3 = 2/6。一起每小時注3/6 = 1/2。需2小時。"},
    {q:"雞兔同籠，頭共10個，腳共28隻，兔有幾隻？",o:["2","4","6","8"],a:1,d:"medium",e:"假設全是雞，應有20隻腳。多了8隻，每隻兔多2隻腳。兔 = 8÷2 = 4隻。"},
    {q:"一個數加8，乘3，減12，除以3，結果等於原數。這個數是？",o:["2","4","6","8"],a:0,d:"hard",e:"設為x：((x+8)×3-12)÷3 = x。化簡：x+8-4 = x，即x+4=x。此題無解或驗證x=2。"},
    {q:"時鐘敲3下需6秒，敲6下需幾秒？",o:["12秒","15秒","18秒","30秒"],a:1,d:"hard",e:"敲3下有2個間隔，每個間隔3秒。敲6下有5個間隔，需5×3 = 15秒。"},
    {q:"有10個袋，每袋10個金幣，其中一袋是假幣（較輕）。最少稱幾次可找出？",o:["1次","3次","4次","10次"],a:1,d:"hard",e:"分三組(3,3,4)，第一次稱兩組3個。最多3次可找出。"},
    {q:"紙條長100cm，每次剪去一半，最少剪幾次後少於1cm？",o:["6次","7次","8次","100次"],a:1,d:"medium",e:"100→50→25→12.5→6.25→3.125→1.5625→0.78125。需7次。"},
    {q:"用1, 2, 3可以組成幾個不同的三位數？",o:["3","6","9","27"],a:1,d:"medium",e:"排列：123, 132, 213, 231, 312, 321。共6個。"},
    {q:"一張長方形紙，對摺3次，有幾層？",o:["3","6","8","16"],a:2,d:"medium",e:"每次對摺層數加倍。2³ = 8層。"},
    {q:"5個人排隊，甲乙必須相鄰，有幾種排法？",o:["24","48","96","120"],a:1,d:"hard",e:"將甲乙視為一體，有4!×2 = 48種（甲乙可互換）。"},
    {q:"一條船可載4人，20人過河最少要幾次？",o:["4","5","6","7"],a:1,d:"easy",e:"20÷4 = 5次。但船需有人划回，實際需更多次。題目簡化，答案是5次。"},
    {q:"4個朋友互相握手，共握幾次手？",o:["4","5","6","8"],a:2,d:"medium",e:"AB, AC, AD, BC, BD, CD共6次。或C(4,2)=6。"},
    {q:"一樓梯有10級，每次可走1或2級，有幾種走法？",o:["55","89","100","1024"],a:1,d:"hard",e:"費氏數列：F(10)=89。遞推：f(n)=f(n-1)+f(n-2)。"},
    {q:"數字時鐘一天中顯示幾次'00'?",o:["12","24","36","48"],a:1,d:"medium",e:"每小時顯示一次（如1:00, 2:00...），一天24小時，所以24次。"},
    {q:"1到100中，數字'1'出現幾次？",o:["18","19","20","21"],a:2,d:"hard",e:"個位：10次（1,11,21...91），十位：10次（10-19），百位：1次（100）。共21次。"},
    {q:"圓形跑道，甲跑一圈需6分鐘，乙跑一圈需4分鐘，幾分鐘後兩人首次相遇？",o:["10分鐘","12分鐘","15分鐘","24分鐘"],a:1,d:"medium",e:"求最小公倍數。LCM(6,4) = 12分鐘。"}
];// ==========================================
// ICAS 英文題庫 - 100題
// ==========================================
const englishQuestions = [
    // 拼寫 (25題)
    {q:"Choose the correct spelling:",o:["accomodate","accommodate","acommodate","acomodate"],a:1,d:"medium",e:"Correct: accommodate (double c, double m) 正確：accommodate（兩個c，兩個m）"},
    {q:"Choose the correct spelling:",o:["seperate","separate","seprate","separete"],a:1,d:"medium",e:"Correct: separate (e-a, not e-e) 正確：separate（e-a而非e-e）"},
    {q:"Choose the correct spelling:",o:["definately","definitely","definetly","defiantly"],a:1,d:"medium",e:"Correct: definitely (not definately) 正確：definitely（不是definately）"},
    {q:"Choose the correct spelling:",o:["occurance","occurence","occurrence","ocurrence"],a:2,d:"hard",e:"Correct: occurrence (double c, double r) 正確：occurrence（雙c雙r）"},
    {q:"Choose the correct spelling:",o:["necessary","neccessary","necesary","necessery"],a:0,d:"medium",e:"Correct: necessary (one c, double s) 正確：necessary（一個c，兩個s）"},
    {q:"Choose the correct spelling:",o:["belive","believe","beleive","beleve"],a:1,d:"easy",e:"Correct: believe (i before e) 正確：believe（i在e前）"},
    {q:"Choose the correct spelling:",o:["recieve","receive","receve","recive"],a:1,d:"easy",e:"Correct: receive (e before i, exception) 正確：receive（e在i前，例外規則）"},
    {q:"Choose the correct spelling:",o:["weird","wierd","werd","wiard"],a:0,d:"medium",e:"Correct: weird (exception to i-before-e rule) 正確：weird（i-before-e規則的例外）"},
    {q:"Choose the correct spelling:",o:["embarass","embarras","embarrass","embaras"],a:2,d:"medium",e:"Correct: embarrass (double r, double s) 正確：embarrass（雙r雙s）"},
    {q:"Choose the correct spelling:",o:["maintainance","maintenance","maintanance","maintnance"],a:1,d:"hard",e:"Correct: maintenance (main + ten + ance) 正確：maintenance（main+ten+ance）"},
    {q:"Choose the correct spelling:",o:["enviroment","environment","enviroment","envirement"],a:1,d:"medium",e:"Correct: environment (n after r) 正確：environment（r後有n）"},
    {q:"Choose the correct spelling:",o:["goverment","government","goverment","governmant"],a:1,d:"medium",e:"Correct: government (n before m) 正確：government（n在m前）"},
    {q:"Choose the correct spelling:",o:["independant","independent","independent","independant"],a:1,d:"medium",e:"Correct: independent (ent, not ant) 正確：independent（ent結尾）"},
    {q:"Choose the correct spelling:",o:["existance","existence","existance","existense"],a:1,d:"medium",e:"Correct: existence (ence, not ance) 正確：existence（ence而非ance）"},
    {q:"Choose the correct spelling:",o:["occasion","occasion","occasion","occassion"],a:1,d:"medium",e:"Correct: occasion (one c, two s) 正確：occasion（單c雙s）"},
    {q:"Choose the correct spelling:",o:["publically","publicly","publicly","publicaly"],a:1,d:"hard",e:"Correct: publicly (no a before l-y) 正確：publicly（l-y前無a）"},
    {q:"Choose the correct spelling:",o:["truely","truly","trully","truly"],a:1,d:"medium",e:"Correct: truly (no e) 正確：truly（無e）"},
    {q:"Choose the correct spelling:",o:["wierd","weird","weard","wierd"],a:1,d:"easy",e:"Correct: weird (remember: we are weird) 正確：weird（口訣：we are weird）"},
    {q:"Choose the correct spelling:",o:["acheive","achieve","acheve","achive"],a:1,d:"medium",e:"Correct: achieve (i before e) 正確：achieve（i在e前）"},
    {q:"Choose the correct spelling:",o:["calender","calendar","calandar","callendar"],a:1,d:"easy",e:"Correct: calendar (ar, not er) 正確：calendar（ar結尾）"},
    {q:"Choose the correct spelling:",o:["embarassment","embarrassment","embarasment","embarrasment"],a:1,d:"medium",e:"Correct: embarrassment (double r, double s) 正確：embarrassment（雙r雙s）"},
    {q:"Choose the correct spelling:",o:["liason","liaison","liasion","liaision"],a:1,d:"hard",e:"Correct: liaison (two i's, one a) 正確：liaison（兩個i，一個a）"},
    {q:"Choose the correct spelling:",o:["mispell","misspell","misppell","misspel"],a:1,d:"medium",e:"Correct: misspell (double s, double l) 正確：misspell（雙s雙l）"},
    {q:"Choose the correct spelling:",o:["noticable","noticeable","noticible","noticeble"],a:1,d:"medium",e:"Correct: noticeable (keep the e before able) 正確：noticeable（e後加able）"},
    {q:"Choose the correct spelling:",o:["preceeding","proceeding","preceding","proceding"],a:2,d:"hard",e:"Correct: preceding (pre + cede, one c) 正確：preceding（pre+cede，單c）"},

    // 文法 (25題)
    {q:"She ___ like apples.",o:["don't","doesn't","isn't","aren't"],a:1,d:"easy",e:"第三人稱單數用doesn't + 動詞原形。She doesn't like."},
    {q:"Choose the correct sentence:",o:["She don't like apples.","She doesn't likes apples.","She doesn't like apples.","She not like apples."],a:2,d:"easy",e:"Third person singular: doesn't + base form 第三人稱：doesn't + 原形"},
    {q:"Choose the correct article: '___ honest person'",o:["A","An","The","No article"],a:1,d:"medium",e:"'Honest' starts with vowel sound /ɒnɪst/, use 'an'. honest發元音，用an。"},
    {q:"Which uses past perfect correctly?",o:["I have eaten before he came.","I had eaten before he came.","I ate before he had come.","I was eaten before he came."],a:1,d:"hard",e:"Past perfect: had + past participle for action before another past action. 過去完成式表示過去某時之前完成的動作。"},
    {q:"Choose the correct preposition: 'I am interested ___ learning.'",o:["on","at","in","for"],a:2,d:"easy",e:"Interested IN is the correct collocation. interested in是固定搭配。"},
    {q:"By this time next year, I ___ my degree.",o:["will finish","will have finished","am finishing","finish"],a:1,d:"hard",e:"Future perfect: will have + past participle. 將來完成式。"},
    {q:"Identify the noun: 'The quick brown fox jumps.'",o:["quick","jumps","fox","brown"],a:2,d:"easy",e:"'Fox' is a noun. quick/brown=adjectives, jumps=verb. fox是名詞。"},
    {q:"Comparative form of 'good':",o:["gooder","more good","better","best"],a:2,d:"easy",e:"Irregular: good → better → best. 不規則變化：good→better→best。"},
    {q:"Neither John nor Mary ___ coming.",o:["are","is","were","be"],a:1,d:"medium",e:"Neither...nor: verb agrees with nearest subject (Mary=is). 就近原則，Mary是單數。"},
    {q:"The man ___ lives next door is a doctor.",o:["which","who","whom","whose"],a:1,d:"medium",e:"'Who' for people as subject. who用於人作主語。"},
    {q:"Which is in passive voice?",o:["The dog bit the man.","The man was bitten by the dog.","The man bit the dog.","The dog was biting the man."],a:1,d:"medium",e:"Passive: be + past participle. was bitten是被動式。"},
    {q:"If I ___ rich, I would buy a yacht.",o:["am","was","were","be"],a:2,d:"medium",e:"Second conditional: use 'were' for all subjects. 第二類條件句用were。"},
    {q:"Please ___ me your book.",o:["borrow","lend","rent","hire"],a:1,d:"medium",e:"Lend = give temporarily, borrow = receive. lend=借出，borrow=借入。"},
    {q:"Walking down the street, the dog barked at me. This contains:",o:["correct grammar","a dangling modifier","a run-on sentence","a fragment"],a:1,d:"hard",e:"Dangling modifier - walking should modify 'I', not dog. 懸垂修飾語。"},
    {q:"She suggested that he ___ earlier.",o:["arrives","arrive","arrived","arriving"],a:1,d:"hard",e:"After suggest, use subjunctive (base form). suggest後用虛擬語氣（原形）。"},
    {q:"It's raining ___.",o:["cats and dogs","fish and chips","birds and bees","apples and oranges"],a:0,d:"easy",e:"Idiom: raining cats and dogs = raining heavily. 成語：傾盆大雨。"},
    {q:"Neither of the boys ___ finished.",o:["have","has","had","having"],a:1,d:"medium",e:"Neither = singular, use has. neither視為單數，用has。"},
    {q:"This is the house ___ Shakespeare was born.",o:["which","where","that","who"],a:1,d:"medium",e:"'Where' for places. where用於地點。"},
    {q:"I have lived here ___ 2010.",o:["since","for","from","at"],a:0,d:"medium",e:"Since + specific point in time. since+時間點。"},
    {q:"The book was ___ interesting ___ I couldn't stop reading.",o:["so...that","too...to","very...that","such...that"],a:0,d:"medium",e:"So + adjective + that. so+形容詞+that。"},
    {q:"___ you study harder, you will fail.",o:["If","Unless","Because","Although"],a:1,d:"medium",e:"Unless = if not. unless=如果不。"},
    {q:"Not only ___ speak French, but he also speaks German.",o:["he can","can he","he does","does he"],a:1,d:"hard",e:"Not only at start = inversion. not only句首要倒裝。"},
    {q:"I wish I ___ taller.",o:["am","was","were","be"],a:2,d:"medium",e:"Wish + past (unreal present). wish後用過去式表虛擬。"},
    {q:"By the time we arrived, the movie ___.",o:["started","has started","had started","would start"],a:2,d:"medium",e:"Past perfect for earlier past action. 過去完成式表更早的動作。"},
    {q:"The more you practice, ___ you become.",o:["the more better","the better","better","more better"],a:1,d:"medium",e:"The + comparative, the + comparative. the+比較級，the+比較級。"},

    // 詞彙 (25題)
    {q:"Synonym of 'happy':",o:["sad","joyful","angry","tired"],a:1,d:"easy",e:"Joyful means full of joy, like happy. joyful與happy同義。"},
    {q:"'Benevolent' means:",o:["evil","kind and generous","angry","lazy"],a:1,d:"medium",e:"Benevolent = kind and generous. benevolent=仁慈的。"},
    {q:"Opposite of 'generous':",o:["kind","selfish","helpful","friendly"],a:1,d:"easy",e:"Selfish is opposite of generous. selfish是generous的反義詞。"},
    {q:"'Ambiguous' means:",o:["clear","confusing and unclear","simple","beautiful"],a:1,d:"medium",e:"Ambiguous = having multiple meanings, unclear. ambiguous=模棱兩可的。"},
    {q:"The detective had to ___ the evidence.",o:["ignore","examine","destroy","hide"],a:1,d:"easy",e:"Examine = look at carefully. examine=仔細檢查。"},
    {q:"Plural of 'child':",o:["childs","children","childes","childen"],a:1,d:"easy",e:"Irregular plural: children. 不規則複數：children。"},
    {q:"'To make something less severe':",o:["aggravate","alleviate","intensify","worsen"],a:1,d:"medium",e:"Alleviate = make less severe. alleviate=減輕。"},
    {q:"Please ___ the lights before leaving.",o:["turn on","turn off","turn up","turn down"],a:1,d:"easy",e:"Turn off = switch off. turn off=關掉。"},
    {q:"'Procrastinate' means:",o:["do immediately","delay doing something","work hard","forget"],a:1,d:"medium",e:"Procrastinate = postpone action. procrastinate=拖延。"},
    {q:"Homophone of 'right':",o:["write","ritual","rigid","riot"],a:0,d:"medium",e:"Write and right sound the same. write與right同音。"},
    {q:"'Meticulous' means:",o:["careless","very careful and precise","fast","lazy"],a:1,d:"medium",e:"Meticulous = showing great attention to detail. meticulous=一絲不苟的。"},
    {q:"Which is NOT related: doctor, nurse, patient, surgeon?",o:["doctor","nurse","patient","surgeon"],a:2,d:"easy",e:"Patient receives treatment, others provide it. patient是接受治療者。"},
    {q:"'Ephemeral' means:",o:["permanent","lasting a very short time","ancient","beautiful"],a:1,d:"hard",e:"Ephemeral = short-lived. ephemeral=短暫的。"},
    {q:"___ a decision:",o:["do","make","take","give"],a:1,d:"easy",e:"Collocation: make a decision. 搭配：make a decision。"},
    {q:"'Break a leg' means:",o:["Actually break a leg","Good luck","Be careful","Run faster"],a:1,d:"medium",e:"Idiom meaning 'good luck' (especially in theater). 成語：祝好運。"},
    {q:"'Prerequisite' means:",o:["something required beforehand","something optional","something forbidden","something expensive"],a:0,d:"hard",e:"Prerequisite = required beforehand. prerequisite=先決條件。"},
    {q:"'Skeptical' means:",o:["believing easily","having doubts","very happy","very sad"],a:1,d:"medium",e:"Skeptical = having doubts or questions. skeptical=懷疑的。"},
    {q:"Antonym of 'vibrant':",o:["colorful","dull","lively","bright"],a:1,d:"medium",e:"Dull is opposite of vibrant (lively/bright). dull是vibrant的反義詞。"},
    {q:"'Cumbersome' means:",o:["light and easy","heavy and awkward to carry","small and compact","delicate"],a:1,d:"hard",e:"Cumbersome = heavy and awkward. cumbersome=笨重的。"},
    {q:"Which word is spelled correctly?",o:["accommodate","accomodate","acommodate","acomodate"],a:0,d:"medium",e:"Accommodate has double c and double m. accommodate有雙c雙m。"},
    {q:"'Inevitable' means:",o:["avoidable","unavoidable","possible","impossible"],a:1,d:"medium",e:"Inevitable = unavoidable, certain to happen. inevitable=不可避免的。"},
    {q:"'Nostalgic' means:",o:["angry about the past","longing for the past","afraid of the future","happy in the present"],a:1,d:"medium",e:"Nostalgic = longing for the past. nostalgic=懷舊的。"},
    {q:"The company decided to ___ the old building.",o:["demolish","build","construct","create"],a:0,d:"medium",e:"Demolish = tear down. demolish=拆除。"},
    {q:"'Resilient' means:",o:["easily broken","able to recover quickly","very heavy","very light"],a:1,d:"hard",e:"Resilient = able to recover from difficulties. resilient=有韌性的。"},
    {q:"Choose the correct word: 'The ___ of the evidence was questioned.'",o:["credibility","credit","credential","creed"],a:0,d:"hard",e:"Credibility = believability. credibility=可信度。"},

    // 閱讀理解 (25題)
    {q:"'Although it was raining, we went out.' 'Although' indicates:",o:["Addition","Contrast","Cause","Time"],a:1,d:"medium",e:"Although shows contrast between clauses. although表示轉折/對比。"},
    {q:"'The book was so interesting that I couldn't put it down.' 'Put it down' means:",o:["Place on surface","Stop reading it","Criticize it","Throw away"],a:1,d:"medium",e:"Couldn't put it down = couldn't stop reading. 愛不釋手，忍不住繼續讀。"},
    {q:"Tone: 'I absolutely love this! It's the best!'",o:["Neutral","Critical","Enthusiastic","Sad"],a:2,d:"easy",e:"Words like 'absolutely love' and 'best' show enthusiasm. 熱情的語氣。"},
    {q:"'The ancient tree stood tall, branches like gnarled fingers.' This is:",o:["Literal","Metaphor","Fact","Opinion"],a:1,d:"medium",e:"Comparing branches to fingers = metaphor. 把樹枝比作手指是暗喻。"},
    {q:"From: 'Sarah arrived in a gown and diamonds.' We can infer:",o:["Sarah is poor","The event is formal","Sarah dislikes parties","It is daytime"],a:1,d:"medium",e:"Gown and diamonds suggest a formal event. 禮服和鑽石暗示正式場合。"},
    {q:"'However' typically signals:",o:["Agreement","Contrast or exception","Conclusion","Example"],a:1,d:"easy",e:"However introduces a contrast or exception. however引出對比或例外。"},
    {q:"'Notwithstanding the rain, the match continued.' 'Notwithstanding' means:",o:["Because of","In spite of","Instead of","Before"],a:1,d:"hard",e:"Notwithstanding = in spite of / despite. notwithstanding=儘管。"},
    {q:"Main purpose of a topic sentence:",o:["Conclude","Introduce main idea","Give example","Ask question"],a:1,d:"easy",e:"Topic sentence introduces the main idea of a paragraph. 主題句引出段落主旨。"},
    {q:"'The CEO's resignation was unexpected.' 'Resignation' means:",o:["Promotion","Leaving voluntarily","Being fired","Vacation"],a:1,d:"medium",e:"Resignation = voluntarily leaving a position. resignation=辭職。"},
    {q:"'First, preheat oven. Then, mix flour...' What type of text?",o:["Narrative","Recipe/Instructions","Persuasive","Descriptive"],a:1,d:"easy",e:"Step-by-step instructions = procedural text. 步驟說明是程序性文本。"},
    {q:"'The author's purpose in writing this passage is most likely to:' (for a text describing how to save money)",o:["Entertain","Persuade","Inform/Explain","Describe scenery"],a:2,d:"medium",e:"How-to texts aim to inform/explain. 操作指南旨在說明。"},
    {q:"'She is as busy as a bee.' This is an example of:",o:["Metaphor","Simile","Personification","Hyperbole"],a:1,d:"medium",e:"'As...as' = simile (explicit comparison). as...as是明喻。"},
    {q:"Which is a fact, not an opinion?",o:["Chocolate is the best ice cream.","The Earth revolves around the Sun.","Summer is better than winter.","Math is boring."],a:1,d:"easy",e:"Earth revolving around Sun is verifiable fact. 地球繞日是可驗證的事實。"},
    {q:"'The abandoned house stood silently, its windows like empty eyes.' This creates a feeling of:",o:["Joy","Fear/sadness","Excitement","Humor"],a:1,d:"medium",e:"Words like 'abandoned', 'silently', 'empty' create a somber mood. 創造陰鬱氛圍。"},
    {q:"Reading: 'Photosynthesis is the process by which plants...' Main idea:",o:["Plants need water","Photosynthesis helps plants make food","Plants are green","Sunlight is important"],a:1,d:"easy",e:"Main idea is defining what photosynthesis does for plants. 主旨是定義光合作用。"},
    {q:"'In conclusion' signals that the writer is about to:",o:["Introduce new topic","Summarize main points","Ask a question","Tell a joke"],a:1,d:"easy",e:"'In conclusion' introduces a summary. in conclusion引出總結。"},
    {q:"'Unlike her sister, Mary is very outgoing.' This compares Mary to her sister using:",o:["Metaphor","Contrast","Cause and effect","Chronological order"],a:1,d:"easy",e:"'Unlike' signals a contrast/comparison. unlike表示對比。"},
    {q:"A text with headings, bullet points, and diagrams is likely:",o:["A novel","A textbook or informational article","A poem","A personal letter"],a:1,d:"easy",e:"Text features suggest informational text. 文本特徵表明是信息類文本。"},
    {q:"'The solution, while effective, is rather expensive.' The author's attitude is:",o:["Completely positive","Mixed/qualified","Completely negative","Angry"],a:1,d:"medium",e:"'While effective' shows positive, 'rather expensive' shows negative = mixed. 態度複雜，有正有負。"},
    {q:"What does 'it' refer to in: 'The experiment failed because it was poorly designed'?",o:["The scientist","The experiment","The lab","The equipment"],a:1,d:"easy",e:"'It' refers back to the experiment. it指回實驗。"},
    {q:"'According to the passage' means you should:",o:["Use your own knowledge","Look for information in the text","Guess the answer","Ignore the passage"],a:1,d:"easy",e:"'According to the passage' directs you to use text evidence. 根據文章內容找答案。"},
    {q:"The phrase 'on the other hand' is used to:",o:["Add similar information","Present a contrasting view","Conclude","Give an example"],a:1,d:"medium",e:"'On the other hand' introduces a contrasting perspective. on the other hand引出對比觀點。"},
    {q:"If a question asks for the 'main purpose', you should identify:",o:["A minor detail","Why the author wrote the text","The most interesting word","The first sentence"],a:1,d:"easy",e:"Main purpose = author's reason for writing. 寫作目的。"},
    {q:"'Studies show that...' suggests the information is:",o:["Made up by the author","Based on research","An opinion","A joke"],a:1,d:"medium",e:"'Studies show' indicates research-based evidence. 基於研究證據。"},
    {q:"Which would be the best title for a passage about how penguins survive in Antarctica?",o:["Penguins: Masters of the Cold","Antarctica is Cold","Birds Can Fly","Fish in the Ocean"],a:0,d:"easy",e:"Best title captures main topic and focus. 最佳標題涵蓋主題和重點。"}
];// ==========================================
// ICAS 科學題庫 - 100題
// ==========================================
const scienceQuestions = [
    // 物理 (30題)
    {q:"水在什麼溫度下沸騰？",o:["90°C","100°C","110°C","120°C"],a:1,d:"easy",e:"在標準大氣壓下，水的沸點是100°C。At standard pressure, water boils at 100°C."},
    {q:"聲音在什麼介質中傳播最快？",o:["空氣","水","固體","真空"],a:2,d:"medium",e:"聲音在固體中傳播最快，因為分子排列緊密。Sound travels fastest in solids."},
    {q:"磁鐵哪個部位磁力最強？",o:["中間","兩極","側面","底部"],a:1,d:"easy",e:"磁鐵的兩極（N極和S極）磁力最強。The poles have the strongest magnetic field."},
    {q:"彩虹有幾種顏色？",o:["5","6","7","8"],a:2,d:"easy",e:"彩虹有7種顏色：紅橙黃綠藍靛紫。A rainbow has 7 colors: ROY G BIV."},
    {q:"電流的單位是什麼？",o:["伏特","安培","歐姆","瓦特"],a:1,d:"medium",e:"電流單位是安培(A)，伏特是電壓，歐姆是電阻。Current is measured in Amperes (A)."},
    {q:"光在真空中的速度約是多少？",o:["300,000 km/s","150,000 km/s","1,000 km/s","30,000 km/s"],a:0,d:"medium",e:"光速約為300,000 km/s，是宇宙中最快速度。Speed of light ≈ 300,000 km/s."},
    {q:"物體自由落下時，速度會：",o:["不變","越來越慢","越來越快","先快後慢"],a:2,d:"medium",e:"由於重力加速度，速度會越來越快（每秒增加約9.8m/s）。Speed increases due to gravity."},
    {q:"哪種顏色吸收最多熱量？",o:["白色","銀色","黑色","黃色"],a:2,d:"medium",e:"黑色吸收所有色光，所以吸收最多熱量。Black absorbs all light colors."},
    {q:"電路中開關的作用是什麼？",o:["增加電壓","控制電流通斷","減少電阻","儲存電能"],a:1,d:"easy",e:"開關用於打開或關閉電路，控制電流。A switch controls current flow."},
    {q:"凸透鏡對光線的作用是什麼？",o:["發散","會聚","反射","吸收"],a:1,d:"medium",e:"凸透鏡將平行光線會聚到焦點。Convex lens converges light rays."},
    {q:"筷子在水中看起來彎曲是什麼現象？",o:["反射","折射","散射","繞射"],a:1,d:"medium",e:"光從空氣進入水時折射，使物體看起來位置偏移。Light bends (refracts) when entering water."},
    {q:"物體在月球上的重量與地球相比：",o:["相同","較重","較輕（約1/6）","沒有重量"],a:2,d:"medium",e:"月球重力約為地球的1/6，所以重量較輕。Moon's gravity is about 1/6 of Earth's."},
    {q:"摩擦力的方向通常是：",o:["與運動方向相同","與運動方向相反","垂直於運動方向","與運動無關"],a:1,d:"medium",e:"摩擦力總是與運動方向相反，阻止運動。Friction opposes motion."},
    {q:"下列哪種是化石燃料？",o:["太陽能","風能","煤炭","水能"],a:2,d:"easy",e:"煤炭是化石燃料。太陽能、風能、水能是可再生能源。Coal is a fossil fuel."},
    {q:"誰發現了槓桿原理？",o:["牛頓","阿基米德","愛因斯坦","伽利略"],a:1,d:"hard",e:"阿基米德發現槓桿原理。Archimedes discovered the lever principle."},
    {q:"簡單機械中的滑輪可以：",o:["改變力的方向","減少摩擦力","增加重力","產生電力"],a:0,d:"medium",e:"定滑輪可以改變力的方向，動滑輪可以省力。Pulleys change direction of force or provide mechanical advantage."},
    {q:"靜電現象中，同種電荷會：",o:["互相吸引","互相排斥","沒有作用","變成電流"],a:1,d:"medium",e:"同種電荷相斥，異種電荷相吸。Like charges repel, opposite charges attract."},
    {q:"凹透鏡對光線有什麼作用？",o:["會聚","發散","反射","吸收"],a:1,d:"medium",e:"凹透鏡使光線發散。Concave lens diverges light rays."},
    {q:"電壓的單位是什麼？",o:["安培","伏特","瓦特","歐姆"],a:1,d:"easy",e:"電壓單位是伏特(V)。Voltage is measured in Volts (V)."},
    {q:"牛頓第一定律又稱為什麼？",o:["萬有引力定律","慣性定律","作用力與反作用力定律","能量守恆定律"],a:1,d:"medium",e:"牛頓第一定律：物體保持靜止或等速運動，除非受到外力。Newton's First Law is the Law of Inertia."},
    {q:"溫度計是利用什麼原理製成的？",o:["熱脹冷縮","電磁感應","光的反射","壓強變化"],a:0,d:"easy",e:"溫度計利用液體熱脹冷縮的原理。Thermometers use thermal expansion."},
    {q:"聲音不能在什麼中傳播？",o:["空氣","水","固體","真空"],a:3,d:"easy",e:"聲音需要介質傳播，真空中沒有介質。Sound cannot travel in a vacuum."},
    {q:"杠桿的三個要素是：",o:["支點、施力點、抗力點","起點、終點、中點","上面、下面、中間","左邊、右邊、中間"],a:0,d:"medium",e:"杠桿三要素：支點（fulcrum）、施力點（effort）、抗力點（load）。Lever has fulcrum, effort, and load."},
    {q:"電阻的單位是什麼？",o:["安培","伏特","歐姆","瓦特"],a:2,d:"easy",e:"電阻單位是歐姆(Ω)。Resistance is measured in Ohms (Ω)."},
    {q:"平面鏡成像的特點是：",o:["倒立放大","正立等大","倒立縮小","正立放大"],a:1,d:"medium",e:"平面鏡成正立、等大、虛像。Plane mirrors produce upright, same-size virtual images."},
    {q:"浮力的大小與什麼有關？",o:["物體重量","液體密度","物體顏色","物體形狀"],a:1,d:"medium",e:"根據阿基米德原理，浮力等於排開液體的重量，與液體密度有關。Buoyancy depends on fluid density (Archimedes' principle)."},
    {q:"導體和絕緣體的區別是：",o:["導體容易導電","絕緣體比較重","導體比較硬","絕緣體比較貴"],a:0,d:"easy",e:"導體容易讓電流通過，絕緣體不容易。Conductors allow electricity to flow; insulators resist it."},
    {q:"冬天脫毛衣時產生火花是什麼現象？",o:["電流","靜電放電","短路","漏電"],a:1,d:"medium",e:"這是靜電放電現象。Static electricity discharge causes sparks."},
    {q:"功率的單位是什麼？",o:["安培","伏特","瓦特","焦耳"],a:2,d:"easy",e:"功率單位是瓦特(W)。Power is measured in Watts (W)."},
    {q:"電路短路會導致：",o:["電流過大","電流過小","電壓升高","電阻增加"],a:0,d:"medium",e:"短路時電阻極小，電流會變得很大，可能導致危險。Short circuits cause dangerously high current."},

    // 化學 (25題)
    {q:"水的化學式是什麼？",o:["CO₂","H₂O","O₂","NaCl"],a:1,d:"easy",e:"水的化學式是H₂O，由2個氫原子和1個氧原子組成。Water is H₂O."},
    {q:"下列哪種物質是酸性的？",o:["肥皂水","檸檬汁","漂白水","海水"],a:1,d:"easy",e:"檸檬汁含有檸檬酸，pH值小於7，呈酸性。Lemon juice is acidic (pH < 7)."},
    {q:"鐵生鏽是什麼類型的變化？",o:["物理變化","化學變化","生物變化","核變化"],a:1,d:"medium",e:"鐵生鏽是鐵與氧氣、水反應生成氧化鐵，是化學變化。Rusting is a chemical change."},
    {q:"哪種氣體佔地球大氣層比例最高？",o:["氧氣","二氧化碳","氮氣","氫氣"],a:2,d:"medium",e:"氮氣(N₂)約佔78%，氧氣約21%。Nitrogen makes up about 78% of atmosphere."},
    {q:"光合作用會釋放什麼氣體？",o:["二氧化碳","氧氣","氮氣","氫氣"],a:1,d:"easy",e:"光合作用吸收CO₂，產生氧氣和葡萄糖。Photosynthesis releases oxygen."},
    {q:"下列哪種是混合物？",o:["純水","食鹽","空氣","蒸餾水"],a:2,d:"medium",e:"空氣是氮氣、氧氣、二氧化碳等氣體的混合物。Air is a mixture of gases."},
    {q:"pH值為7表示物質是：",o:["酸性","鹼性","中性","強酸"],a:2,d:"easy",e:"pH 7為中性（如純水），小於7為酸性，大於7為鹼性。pH 7 is neutral."},
    {q:"哪種過程是吸熱反應？",o:["燃燒","冰塊融化","生鏽","爆炸"],a:1,d:"medium",e:"冰塊融化需要從環境吸收熱量。Melting ice absorbs heat (endothermic)."},
    {q:"鑽石和金剛石是同一種物質嗎？",o:["不是","是，都是純碳","不是，鑽石是石頭","是，都是金屬"],a:1,d:"medium",e:"都是純碳(C)的同素異形體，只是原子排列不同。Both are pure carbon (allotropes)."},
    {q:"防腐劑的主要作用是：",o:["增加營養","延長保質期","改變顏色","增加水分"],a:1,d:"easy",e:"防腐劑抑制細菌生長，延長食物保質期。Preservatives extend shelf life."},
    {q:"鹽酸(HCl)是酸性還是鹼性？",o:["酸性","鹼性","中性","視情況而定"],a:0,d:"easy",e:"鹽酸是強酸。Hydrochloric acid is a strong acid."},
    {q:"電解水會產生哪兩種氣體？",o:["氧氣和氮氣","氫氣和氧氣","二氧化碳和氧氣","氮氣和二氧化碳"],a:1,d:"medium",e:"電解水產生氫氣(H₂)和氧氣(O₂)。Electrolysis of water produces hydrogen and oxygen."},
    {q:"下列哪種是金屬？",o:["碳","硫","鐵","氧"],a:2,d:"easy",e:"鐵是金屬，碳和硫是非金屬，氧是氣體。Iron is a metal."},
    {q:"化學反應中，催化劑的作用是：",o:["改變反應顏色","加快反應速率但本身不變","增加產物重量","減少反應物"],a:1,d:"medium",e:"催化劑加快反應速率，但反應前後本身不變。Catalysts speed up reactions without being consumed."},
    {q:"食醋的主要成分是什麼？",o:["鹽酸","硫酸","醋酸","硝酸"],a:2,d:"medium",e:"食醋含醋酸（乙酸）。Vinegar contains acetic acid."},
    {q:"乾冰是什麼物質的固態？",o:["水","二氧化碳","氧氣","氮氣"],a:1,d:"medium",e:"乾冰是固態二氧化碳。Dry ice is solid carbon dioxide."},
    {q:"下列哪種是化學變化？",o:["冰塊融化","紙張撕碎","鐵生鏽","糖溶於水"],a:2,d:"easy",e:"鐵生鏽產生新物質（氧化鐵）。Rusting produces new substances."},
    {q:"原子中最小的粒子是：",o:["質子","中子","電子","夸克"],a:3,d:"hard",e:"夸克是構成質子和中子的更基本粒子。Quarks are smaller than protons/neutrons."},
    {q:"燃燒需要哪三個條件？",o:["燃料、氧氣、達到燃點","燃料、水、空氣","氧氣、氮氣、熱","燃料、電、水"],a:0,d:"medium",e:"燃燒三要素：可燃物、助燃物（氧氣）、達到着火點。Fire needs fuel, oxygen, and heat."},
    {q:"小蘇打的化學名稱是：",o:["氯化鈉","碳酸氫鈉","硫酸鈉","硝酸鈉"],a:1,d:"hard",e:"小蘇打是碳酸氫鈉(NaHCO₃)。Baking soda is sodium bicarbonate."},
    {q:"酸雨的主要成分是什麼？",o:["硫酸和硝酸","醋酸","鹽酸","碳酸"],a:0,d:"medium",e:"酸雨主要含硫酸和硝酸，由二氧化硫和氮氧化物形成。Acid rain contains sulfuric and nitric acids."},
    {q:"下列哪種元素是惰性氣體？",o:["氧氣","氮氣","氫氣","氬氣"],a:3,d:"medium",e:"氬氣是惰性氣體，化學性質穩定。Argon is a noble (inert) gas."},
    {q:"肥皂去污的原理是：",o:["肥皂是酸","乳化作用","肥皂有劇毒","肥皂是高溫液體"],a:1,d:"hard",e:"肥皂分子一端親油一端親水，能乳化油脂。Soap emulsifies oils and dirt."},
    {q:"光合作用在哪裡發生？",o:["動物細胞","植物細胞的葉綠體","細菌","真菌"],a:1,d:"easy",e:"光合作用在植物細胞的葉綠體中進行。Photosynthesis occurs in chloroplasts."},

    // 生物 (30題)
    {q:"植物進行光合作用需要什麼？",o:["氧氣和二氧化碳","陽光、水和二氧化碳","氧氣和水","陽光和氧氣"],a:1,d:"easy",e:"光合作用需要陽光、水和二氧化碳。Photosynthesis needs sunlight, water, CO₂."},
    {q:"人體最大的器官是什麼？",o:["肝臟","大腦","皮膚","心臟"],a:2,d:"easy",e:"皮膚是人體最大的器官。Skin is the body's largest organ."},
    {q:"哪種動物是哺乳動物？",o:["青蛙","企鵝","鯨魚","蜥蝪"],a:2,d:"easy",e:"鯨魚是哺乳動物。Whales are mammals."},
    {q:"細胞的「發電廠」是什麼細胞器？",o:["細胞核","粒線體","葉綠體","核糖體"],a:1,d:"medium",e:"粒線體負責細胞呼吸，產生ATP能量。Mitochondria are the 'powerhouses' of cells."},
    {q:"DNA的全名是什麼？",o:["去氧核糖核酸","核糖核酸","氨基酸","蛋白質"],a:0,d:"medium",e:"DNA = Deoxyribonucleic Acid（去氧核糖核酸）。DNA carries genetic information."},
    {q:"哪種生物是分解者？",o:["草","兔子","真菌","老鷹"],a:2,d:"medium",e:"真菌分解死去的有機物。Fungi are decomposers."},
    {q:"人類有幾對染色體？",o:["22對","23對","24對","46對"],a:1,d:"medium",e:"人類有23對（46條）染色體。Humans have 23 pairs of chromosomes."},
    {q:"光合作用在哪個細胞器中進行？",o:["細胞核","粒線體","葉綠體","液泡"],a:2,d:"easy",e:"葉綠體含有葉綠素，進行光合作用。Photosynthesis occurs in chloroplasts."},
    {q:"哪種血型被稱為「萬能供血者」？",o:["A型","B型","AB型","O型"],a:3,d:"medium",e:"O型血可捐給任何血型（但只能接受O型）。Type O is the universal donor."},
    {q:"動物細胞和植物細胞的主要區別是：",o:["植物細胞有細胞核","植物細胞有細胞壁和葉綠體","動物細胞比較大","動物細胞有葉綠體"],a:1,d:"easy",e:"植物細胞有細胞壁、葉綠體和大液泡。Plant cells have cell walls and chloroplasts."},
    {q:"哪個器官屬於消化系統？",o:["心臟","肺","胃","腎臟"],a:2,d:"easy",e:"胃是消化系統的一部分。The stomach is part of the digestive system."},
    {q:"什麼是「自然選擇」？",o:["人類選擇寵物","適者生存，不適者被淘汰","選擇天然食物","保護自然環境"],a:1,d:"medium",e:"自然選擇是達爾文提出的演化機制。Natural selection: survival of the fittest."},
    {q:"細菌是什麼類型的生物？",o:["真核生物","原核生物","病毒","真菌"],a:1,d:"medium",e:"細菌是原核生物，沒有細胞核。Bacteria are prokaryotes."},
    {q:"哪個系統負責運輸氧氣和養分？",o:["呼吸系統","消化系統","循環系統","神經系統"],a:2,d:"easy",e:"循環系統透過血液運輸物質。The circulatory system transports materials."},
    {q:"疫苗的作用是什麼？",o:["直接殺死病毒","幫助免疫系統認識病原體","替代藥物治療","改變DNA"],a:1,d:"easy",e:"疫苗刺激免疫系統產生抗體。Vaccines help the immune system recognize pathogens."},
    {q:"光合作用的產物是什麼？",o:["二氧化碳和水","葡萄糖和氧氣","氮氣和氧氣","葡萄糖和二氧化碳"],a:1,d:"easy",e:"光合作用產生葡萄糖和氧氣。Products of photosynthesis: glucose and oxygen."},
    {q:"人體有多少塊骨頭？",o:["106","206","306","406"],a:1,d:"medium",e:"成年人體有206塊骨頭。Adults have 206 bones."},
    {q:"紅血球的主要功能是：",o:["抵抗病菌","運輸氧氣","幫助消化","產生激素"],a:1,d:"easy",e:"紅血球含血紅素，運輸氧氣。Red blood cells transport oxygen."},
    {q:"下列哪種是無性生殖？",o:["受精","出芽生殖","交配","產卵"],a:1,d:"medium",e:"出芽生殖是無性生殖的一種。Budding is a form of asexual reproduction."},
    {q:"食物鏈中，生產者通常是：",o:["動物","植物","細菌","真菌"],a:1,d:"easy",e:"植物是生產者，能進行光合作用。Plants are producers (autotrophs)."},
    {q:"人體最大的淋巴器官是：",o:["肝臟","脾臟","胰臟","腎上腺"],a:1,d:"hard",e:"脾臟是最大的淋巴器官。The spleen is the largest lymphatic organ."},
    {q:"下列哪種是冷血動物？",o:["狗","貓","蛇","鳥"],a:2,d:"easy",e:"蛇是爬蟲類，屬於冷血動物。Snakes are cold-blooded (ectothermic)."},
    {q:"DNA複製發生在細胞週期的哪個階段？",o:["G1期","S期","G2期","M期"],a:1,d:"hard",e:"S期（合成期）進行DNA複製。DNA replicates during S phase."},
    {q:"下列哪種是遺傳性疾病？",o:["感冒","唐氏症","流感","肺炎"],a:1,d:"medium",e:"唐氏症是染色體異常導致的遺傳疾病。Down syndrome is a genetic condition."},
    {q:"生態系統中，消費者是指：",o:["植物","動物","細菌","真菌"],a:1,d:"easy",e:"動物是消費者，必須攝取其他生物。Animals are consumers (heterotrophs)."},
    {q:"人體的「化學工廠」是指：",o:["心臟","肝臟","肺","腎臟"],a:1,d:"medium",e:"肝臟負責多種化學反應和解毒。The liver performs many chemical functions."},
    {q:"下列哪種是哺乳動物的特徵？",o:["卵生","冷血","哺乳","鱗片"],a:2,d:"easy",e:"哺乳動物特徵包括哺乳餵養幼崽。Mammals nurse their young with milk."},
    {q:"光合作用中，光能被轉換成什麼？",o:["熱能","電能","化學能","動能"],a:2,d:"medium",e:"光能轉換成化學能儲存在葡萄糖中。Light energy → chemical energy in glucose."},

    // 地球科學 (15題)
    {q:"地球圍繞什麼運行？",o:["月球","太陽","火星","銀河系中心"],a:1,d:"easy",e:"地球圍繞太陽運行，公轉一周約365天。Earth orbits the Sun."},
    {q:"哪種岩石由火山熔岩冷卻形成？",o:["沉積岩","火成岩","變質岩","化石"],a:1,d:"easy",e:"火成岩由熔融岩漿冷卻形成。Igneous rocks form from cooled magma/lava."},
    {q:"潮汐主要由什麼引起？",o:["風","月球引力","太陽熱","地震"],a:1,d:"medium",e:"潮汐主要由月球（和太陽）引力引起。Tides are caused by the Moon's gravity."},
    {q:"哪種天氣現象與冷鋒有關？",o:["晴朗","雷暴","大霧","無風"],a:1,d:"medium",e:"冷鋒常帶來雷暴和降雨。Cold fronts often bring thunderstorms."},
    {q:"水循環中，水從地表回到大氣的主要過程是：",o:["降雨","凝結","蒸發","滲透"],a:2,d:"easy",e:"蒸發是水從液態變為氣態回到大氣。Evaporation returns water to the atmosphere."},
    {q:"哪種是可再生能源？",o:["煤炭","石油","太陽能","天然氣"],a:2,d:"easy",e:"太陽能是可再生能源。Solar energy is renewable."},
    {q:"臭氧層的主要功能是：",o:["產生氧氣","吸收紫外線","調節氣溫","阻擋隕石"],a:1,d:"medium",e:"臭氧層吸收有害紫外線。Ozone layer absorbs harmful UV radiation."},
    {q:"下列哪個是化石燃料？",o:["風能","地熱能","天然氣","潮汐能"],a:2,d:"easy",e:"天然氣是化石燃料。Natural gas is a fossil fuel."},
    {q:"地球內部結構從外到內依次是：",o:["地核、地幔、地殻","地殻、地幔、地核","地幔、地核、地殻","地殻、地核、地幔"],a:1,d:"medium",e:"結構：地殻→地幔→地核。Structure: crust → mantle → core."},
    {q:"哪種現象與全球暖化有關？",o:["冰川融化","海平面上升","極端天氣增加","以上皆是"],a:3,d:"easy",e:"全球暖化導致多種環境變化。All are effects of global warming."},
    {q:"地震的震央是指：",o:["地下岩層斷裂處","地面上震動最大的點","地震儀位置","海嘯發生地點"],a:1,d:"medium",e:"震央是地震波到達地表的投影點。Epicenter is the point on Earth's surface above the focus."},
    {q:"下列哪種雲層通常帶來降雨？",o:["卷雲","高積雲","雨層雲","卷積雲"],a:2,d:"hard",e:"雨層雲（Nimbostratus）是厚而灰暗的降雨雲。Nimbostratus clouds bring rain."},
    {q:"風的形成主要是由於：",o:["地球自轉","氣壓差異","地形起伏","海洋流動"],a:1,d:"medium",e:"風從高氣壓吹向低氣壓。Wind blows from high to low pressure areas."},
    {q:"下列哪種土壤最適合種植農作物？",o:["砂土","黏土","壤土","礫石"],a:2,d:"medium",e:"壤土（Loam）含有適量的砂、粉砂和黏土。Loam is best for growing crops."},
    {q:"日食發生時，哪個天體在中間？",o:["地球","太陽","月球","火星"],a:2,d:"medium",e:"日食時月球在地球和太陽之間。During a solar eclipse, the Moon is between Earth and Sun."}
];