// ==========================================
// ICAS 英文題庫 - 100題
// ==========================================
const englishQuestions = [
    // 拼寫 (25題)
    {q:"Choose the correct spelling:",o:["accomodate","accommodate","acommodate","acomodate"],a:1,d:"medium",e:"Correct: accommodate (double c, double m) 正確：accommodate（兩個c，兩個m）"},
    {q:"Choose the correct spelling:",o:["seperate","separate","seprate","separete"],a:1,d:"medium",e:"Correct: separate (e-a, not e-e) 正確：separate（e-a而非e-e）"},
    {q:"Choose the correct spelling:",o:["definately","definitely","definetly","defiantly"],a:1,d:"medium",e:"Correct: definitely (not definately) 正確：definitely（不是definately）"},
    {q:"Choose the correct spelling:",o:["occurance","occurence","occurrence","ocurrence"],a:2,d:"hard",e:"Correct: occurrence (double c, double r) 正確：occurrence（雙c雙r）"},
    {q:"Choose the correct spelling:",o:["necessary","neccessary","necesary","necessery"],a:0,d:"medium",e:"Correct: necessary (one c, double s) 正確：necessary（一個c，兩個s）"},
    {q:"Choose the correct spelling:",o:["belive","believe","beleive","beleve"],a:1,d:"easy",e:"Correct: believe (i before e) 正確：believe（i在e前）"},
    {q:"Choose the correct spelling:",o:["recieve","receive","receve","recive"],a:1,d:"easy",e:"Correct: receive (e before i, exception) 正確：receive（e在i前，例外規則）"},
    {q:"Choose the correct spelling:",o:["weird","wierd","werd","wiard"],a:0,d:"medium",e:"Correct: weird (exception to i-before-e rule) 正確：weird（i-before-e規則的例外）"},
    {q:"Choose the correct spelling:",o:["embarass","embarras","embarrass","embaras"],a:2,d:"medium",e:"Correct: embarrass (double r, double s) 正確：embarrass（雙r雙s）"},
    {q:"Choose the correct spelling:",o:["maintainance","maintenance","maintanance","maintnance"],a:1,d:"hard",e:"Correct: maintenance (main + ten + ance) 正確：maintenance（main+ten+ance）"},
    {q:"Choose the correct spelling:",o:["enviroment","environment","enviroment","envirement"],a:1,d:"medium",e:"Correct: environment (n after r) 正確：environment（r後有n）"},
    {q:"Choose the correct spelling:",o:["goverment","government","goverment","governmant"],a:1,d:"medium",e:"Correct: government (n before m) 正確：government（n在m前）"},
    {q:"Choose the correct spelling:",o:["independant","independent","independent","independant"],a:1,d:"medium",e:"Correct: independent (ent, not ant) 正確：independent（ent結尾）"},
    {q:"Choose the correct spelling:",o:["existance","existence","existance","existense"],a:1,d:"medium",e:"Correct: existence (ence, not ance) 正確：existence（ence而非ance）"},
    {q:"Choose the correct spelling:",o:["occasion","occasion","occasion","occassion"],a:1,d:"medium",e:"Correct: occasion (one c, two s) 正確：occasion（單c雙s）"},
    {q:"Choose the correct spelling:",o:["publically","publicly","publicly","publicaly"],a:1,d:"hard",e:"Correct: publicly (no a before l-y) 正確：publicly（l-y前無a）"},
    {q:"Choose the correct spelling:",o:["truely","truly","trully","truly"],a:1,d:"medium",e:"Correct: truly (no e) 正確：truly（無e）"},
    {q:"Choose the correct spelling:",o:["wierd","weird","weard","wierd"],a:1,d:"easy",e:"Correct: weird (remember: we are weird) 正確：weird（口訣：we are weird）"},
    {q:"Choose the correct spelling:",o:["acheive","achieve","acheve","achive"],a:1,d:"medium",e:"Correct: achieve (i before e) 正確：achieve（i在e前）"},
    {q:"Choose the correct spelling:",o:["calender","calendar","calandar","callendar"],a:1,d:"easy",e:"Correct: calendar (ar, not er) 正確：calendar（ar結尾）"},
    {q:"Choose the correct spelling:",o:["embarassment","embarrassment","embarasment","embarrasment"],a:1,d:"medium",e:"Correct: embarrassment (double r, double s) 正確：embarrassment（雙r雙s）"},
    {q:"Choose the correct spelling:",o:["liason","liaison","liasion","liaision"],a:1,d:"hard",e:"Correct: liaison (two i's, one a) 正確：liaison（兩個i，一個a）"},
    {q:"Choose the correct spelling:",o:["mispell","misspell","misppell","misspel"],a:1,d:"medium",e:"Correct: misspell (double s, double l) 正確：misspell（雙s雙l）"},
    {q:"Choose the correct spelling:",o:["noticable","noticeable","noticible","noticeble"],a:1,d:"medium",e:"Correct: noticeable (keep the e before able) 正確：noticeable（e後加able）"},
    {q:"Choose the correct spelling:",o:["preceeding","proceeding","preceding","proceding"],a:2,d:"hard",e:"Correct: preceding (pre + cede, one c) 正確：preceding（pre+cede，單c）"},

    // 文法 (25題)
    {q:"She ___ like apples.",o:["don't","doesn't","isn't","aren't"],a:1,d:"easy",e:"第三人稱單數用doesn't + 動詞原形。She doesn't like."},
    {q:"Choose the correct sentence:",o:["She don't like apples.","She doesn't likes apples.","She doesn't like apples.","She not like apples."],a:2,d:"easy",e:"Third person singular: doesn't + base form 第三人稱：doesn't + 原形"},
    {q:"Choose the correct article: '___ honest person'",o:["A","An","The","No article"],a:1,d:"medium",e:"'Honest' starts with vowel sound /ɒnɪst/, use 'an'. honest發元音，用an。"},
    {q:"Which uses past perfect correctly?",o:["I have eaten before he came.","I had eaten before he came.","I ate before he had come.","I was eaten before he came."],a:1,d:"hard",e:"Past perfect: had + past participle for action before another past action. 過去完成式表示過去某時之前完成的動作。"},
    {q:"Choose the correct preposition: 'I am interested ___ learning.'",o:["on","at","in","for"],a:2,d:"easy",e:"Interested IN is the correct collocation. interested in是固定搭配。"},
    {q:"By this time next year, I ___ my degree.",o:["will finish","will have finished","am finishing","finish"],a:1,d:"hard",e:"Future perfect: will have + past participle. 將來完成式。"},
    {q:"Identify the noun: 'The quick brown fox jumps.'",o:["quick","jumps","fox","brown"],a:2,d:"easy",e:"'Fox' is a noun. quick/brown=adjectives, jumps=verb. fox是名詞。"},
    {q:"Comparative form of 'good':",o:["gooder","more good","better","best"],a:2,d:"easy",e:"Irregular: good → better → best. 不規則變化：good→better→best。"},
    {q:"Neither John nor Mary ___ coming.",o:["are","is","were","be"],a:1,d:"medium",e:"Neither...nor: verb agrees with nearest subject (Mary=is). 就近原則，Mary是單數。"},
    {q:"The man ___ lives next door is a doctor.",o:["which","who","whom","whose"],a:1,d:"medium",e:"'Who' for people as subject. who用於人作主語。"},
    {q:"Which is in passive voice?",o:["The dog bit the man.","The man was bitten by the dog.","The man bit the dog.","The dog was biting the man."],a:1,d:"medium",e:"Passive: be + past participle. was bitten是被動式。"},
    {q:"If I ___ rich, I would buy a yacht.",o:["am","was","were","be"],a:2,d:"medium",e:"Second conditional: use 'were' for all subjects. 第二類條件句用were。"},
    {q:"Please ___ me your book.",o:["borrow","lend","rent","hire"],a:1,d:"medium",e:"Lend = give temporarily, borrow = receive. lend=借出，borrow=借入。"},
    {q:"Walking down the street, the dog barked at me. This contains:",o:["correct grammar","a dangling modifier","a run-on sentence","a fragment"],a:1,d:"hard",e:"Dangling modifier - walking should modify 'I', not dog. 懸垂修飾語。"},
    {q:"She suggested that he ___ earlier.",o:["arrives","arrive","arrived","arriving"],a:1,d:"hard",e:"After suggest, use subjunctive (base form). suggest後用虛擬語氣（原形）。"},
    {q:"It's raining ___.",o:["cats and dogs","fish and chips","birds and bees","apples and oranges"],a:0,d:"easy",e:"Idiom: raining cats and dogs = raining heavily. 成語：傾盆大雨。"},
    {q:"Neither of the boys ___ finished.",o:["have","has","had","having"],a:1,d:"medium",e:"Neither = singular, use has. neither視為單數，用has。"},
    {q:"This is the house ___ Shakespeare was born.",o:["which","where","that","who"],a:1,d:"medium",e:"'Where' for places. where用於地點。"},
    {q:"I have lived here ___ 2010.",o:["since","for","from","at"],a:0,d:"medium",e:"Since + specific point in time. since+時間點。"},
    {q:"The book was ___ interesting ___ I couldn't stop reading.",o:["so...that","too...to","very...that","such...that"],a:0,d:"medium",e:"So + adjective + that. so+形容詞+that。"},
    {q:"___ you study harder, you will fail.",o:["If","Unless","Because","Although"],a:1,d:"medium",e:"Unless = if not. unless=如果不。"},
    {q:"Not only ___ speak French, but he also speaks German.",o:["he can","can he","he does","does he"],a:1,d:"hard",e:"Not only at start = inversion. not only句首要倒裝。"},
    {q:"I wish I ___ taller.",o:["am","was","were","be"],a:2,d:"medium",e:"Wish + past (unreal present). wish後用過去式表虛擬。"},
    {q:"By the time we arrived, the movie ___.",o:["started","has started","had started","would start"],a:2,d:"medium",e:"Past perfect for earlier past action. 過去完成式表更早的動作。"},
    {q:"The more you practice, ___ you become.",o:["the more better","the better","better","more better"],a:1,d:"medium",e:"The + comparative, the + comparative. the+比較級，the+比較級。"},

    // 詞彙 (25題)
    {q:"Synonym of 'happy':",o:["sad","joyful","angry","tired"],a:1,d:"easy",e:"Joyful means full of joy, like happy. joyful與happy同義。"},
    {q:"'Benevolent' means:",o:["evil","kind and generous","angry","lazy"],a:1,d:"medium",e:"Benevolent = kind and generous. benevolent=仁慈的。"},
    {q:"Opposite of 'generous':",o:["kind","selfish","helpful","friendly"],a:1,d:"easy",e:"Selfish is opposite of generous. selfish是generous的反義詞。"},
    {q:"'Ambiguous' means:",o:["clear","confusing and unclear","simple","beautiful"],a:1,d:"medium",e:"Ambiguous = having multiple meanings, unclear. ambiguous=模棱兩可的。"},
    {q:"The detective had to ___ the evidence.",o:["ignore","examine","destroy","hide"],a:1,d:"easy",e:"Examine = look at carefully. examine=仔細檢查。"},
    {q:"Plural of 'child':",o:["childs","children","childes","childen"],a:1,d:"easy",e:"Irregular plural: children. 不規則複數：children。"},
    {q:"'To make something less severe':",o:["aggravate","alleviate","intensify","worsen"],a:1,d:"medium",e:"Alleviate = make less severe. alleviate=減輕。"},
    {q:"Please ___ the lights before leaving.",o:["turn on","turn off","turn up","turn down"],a:1,d:"easy",e:"Turn off = switch off. turn off=關掉。"},
    {q:"'Procrastinate' means:",o:["do immediately","delay doing something","work hard","forget"],a:1,d:"medium",e:"Procrastinate = postpone action. procrastinate=拖延。"},
    {q:"Homophone of 'right':",o:["write","ritual","rigid","riot"],a:0,d:"medium",e:"Write and right sound the same. write與right同音。"},
    {q:"'Meticulous' means:",o:["careless","very careful and precise","fast","lazy"],a:1,d:"medium",e:"Meticulous = showing great attention to detail. meticulous=一絲不苟的。"},
    {q:"Which is NOT related: doctor, nurse, patient, surgeon?",o:["doctor","nurse","patient","surgeon"],a:2,d:"easy",e:"Patient receives treatment, others provide it. patient是接受治療者。"},
    {q:"'Ephemeral' means:",o:["permanent","lasting a very short time","ancient","beautiful"],a:1,d:"hard",e:"Ephemeral = short-lived. ephemeral=短暫的。"},
    {q:"___ a decision:",o:["do","make","take","give"],a:1,d:"easy",e:"Collocation: make a decision. 搭配：make a decision。"},
    {q:"'Break a leg' means:",o:["Actually break a leg","Good luck","Be careful","Run faster"],a:1,d:"medium",e:"Idiom meaning 'good luck' (especially in theater). 成語：祝好運。"},
    {q:"'Prerequisite' means:",o:["something required beforehand","something optional","something forbidden","something expensive"],a:0,d:"hard",e:"Prerequisite = required beforehand. prerequisite=先決條件。"},
    {q:"'Skeptical' means:",o:["believing easily","having doubts","very happy","very sad"],a:1,d:"medium",e:"Skeptical = having doubts or questions. skeptical=懷疑的。"},
    {q:"Antonym of 'vibrant':",o:["colorful","dull","lively","bright"],a:1,d:"medium",e:"Dull is opposite of vibrant (lively/bright). dull是vibrant的反義詞。"},
    {q:"'Cumbersome' means:",o:["light and easy","heavy and awkward to carry","small and compact","delicate"],a:1,d:"hard",e:"Cumbersome = heavy and awkward. cumbersome=笨重的。"},
    {q:"Which word is spelled correctly?",o:["accommodate","accomodate","acommodate","acomodate"],a:0,d:"medium",e:"Accommodate has double c and double m. accommodate有雙c雙m。"},
    {q:"'Inevitable' means:",o:["avoidable","unavoidable","possible","impossible"],a:1,d:"medium",e:"Inevitable = unavoidable, certain to happen. inevitable=不可避免的。"},
    {q:"'Nostalgic' means:",o:["angry about the past","longing for the past","afraid of the future","happy in the present"],a:1,d:"medium",e:"Nostalgic = longing for the past. nostalgic=懷舊的。"},
    {q:"The company decided to ___ the old building.",o:["demolish","build","construct","create"],a:0,d:"medium",e:"Demolish = tear down. demolish=拆除。"},
    {q:"'Resilient' means:",o:["easily broken","able to recover quickly","very heavy","very light"],a:1,d:"hard",e:"Resilient = able to recover from difficulties. resilient=有韌性的。"},
    {q:"Choose the correct word: 'The ___ of the evidence was questioned.'",o:["credibility","credit","credential","creed"],a:0,d:"hard",e:"Credibility = believability. credibility=可信度。"},

    // 閱讀理解 (25題)
    {q:"'Although it was raining, we went out.' 'Although' indicates:",o:["Addition","Contrast","Cause","Time"],a:1,d:"medium",e:"Although shows contrast between clauses. although表示轉折/對比。"},
    {q:"'The book was so interesting that I couldn't put it down.' 'Put it down' means:",o:["Place on surface","Stop reading it","Criticize it","Throw away"],a:1,d:"medium",e:"Couldn't put it down = couldn't stop reading. 愛不釋手，忍不住繼續讀。"},
    {q:"Tone: 'I absolutely love this! It's the best!'",o:["Neutral","Critical","Enthusiastic","Sad"],a:2,d:"easy",e:"Words like 'absolutely love' and 'best' show enthusiasm. 熱情的語氣。"},
    {q:"'The ancient tree stood tall, branches like gnarled fingers.' This is:",o:["Literal","Metaphor","Fact","Opinion"],a:1,d:"medium",e:"Comparing branches to fingers = metaphor. 把樹枝比作手指是暗喻。"},
    {q:"From: 'Sarah arrived in a gown and diamonds.' We can infer:",o:["Sarah is poor","The event is formal","Sarah dislikes parties","It is daytime"],a:1,d:"medium",e:"Gown and diamonds suggest a formal event. 禮服和鑽石暗示正式場合。"},
    {q:"'However' typically signals:",o:["Agreement","Contrast or exception","Conclusion","Example"],a:1,d:"easy",e:"However introduces a contrast or exception. however引出對比或例外。"},
    {q:"'Notwithstanding the rain, the match continued.' 'Notwithstanding' means:",o:["Because of","In spite of","Instead of","Before"],a:1,d:"hard",e:"Notwithstanding = in spite of / despite. notwithstanding=儘管。"},
    {q:"Main purpose of a topic sentence:",o:["Conclude","Introduce main idea","Give example","Ask question"],a:1,d:"easy",e:"Topic sentence introduces the main idea of a paragraph. 主題句引出段落主旨。"},
    {q:"'The CEO's resignation was unexpected.' 'Resignation' means:",o:["Promotion","Leaving voluntarily","Being fired","Vacation"],a:1,d:"medium",e:"Resignation = voluntarily leaving a position. resignation=辭職。"},
    {q:"'First, preheat oven. Then, mix flour...' What type of text?",o:["Narrative","Recipe/Instructions","Persuasive","Descriptive"],a:1,d:"easy",e:"Step-by-step instructions = procedural text. 步驟說明是程序性文本。"},
    {q:"'The author's purpose in writing this passage is most likely to:' (for a text describing how to save money)",o:["Entertain","Persuade","Inform/Explain","Describe scenery"],a:2,d:"medium",e:"How-to texts aim to inform/explain. 操作指南旨在說明。"},
    {q:"'She is as busy as a bee.' This is an example of:",o:["Metaphor","Simile","Personification","Hyperbole"],a:1,d:"medium",e:"'As...as' = simile (explicit comparison). as...as是明喻。"},
    {q:"Which is a fact, not an opinion?",o:["Chocolate is the best ice cream.","The Earth revolves around the Sun.","Summer is better than winter.","Math is boring."],a:1,d:"easy",e:"Earth revolving around Sun is verifiable fact. 地球繞日是可驗證的事實。"},
    {q:"'The abandoned house stood silently, its windows like empty eyes.' This creates a feeling of:",o:["Joy","Fear/sadness","Excitement","Humor"],a:1,d:"medium",e:"Words like 'abandoned', 'silently', 'empty' create a somber mood. 創造陰鬱氛圍。"},
    {q:"Reading: 'Photosynthesis is the process by which plants...' Main idea:",o:["Plants need water","Photosynthesis helps plants make food","Plants are green","Sunlight is important"],a:1,d:"easy",e:"Main idea is defining what photosynthesis does for plants. 主旨是定義光合作用。"},
    {q:"'In conclusion' signals that the writer is about to:",o:["Introduce new topic","Summarize main points","Ask a question","Tell a joke"],a:1,d:"easy",e:"'In conclusion' introduces a summary. in conclusion引出總結。"},
    {q:"'Unlike her sister, Mary is very outgoing.' This compares Mary to her sister using:",o:["Metaphor","Contrast","Cause and effect","Chronological order"],a:1,d:"easy",e:"'Unlike' signals a contrast/comparison. unlike表示對比。"},
    {q:"A text with headings, bullet points, and diagrams is likely:",o:["A novel","A textbook or informational article","A poem","A personal letter"],a:1,d:"easy",e:"Text features suggest informational text. 文本特徵表明是信息類文本。"},
    {q:"'The solution, while effective, is rather expensive.' The author's attitude is:",o:["Completely positive","Mixed/qualified","Completely negative","Angry"],a:1,d:"medium",e:"'While effective' shows positive, 'rather expensive' shows negative = mixed. 態度複雜，有正有負。"},
    {q:"What does 'it' refer to in: 'The experiment failed because it was poorly designed'?",o:["The scientist","The experiment","The lab","The equipment"],a:1,d:"easy",e:"'It' refers back to the experiment. it指回實驗。"},
    {q:"'According to the passage' means you should:",o:["Use your own knowledge","Look for information in the text","Guess the answer","Ignore the passage"],a:1,d:"easy",e:"'According to the passage' directs you to use text evidence. 根據文章內容找答案。"},
    {q:"The phrase 'on the other hand' is used to:",o:["Add similar information","Present a contrasting view","Conclude","Give an example"],a:1,d:"medium",e:"'On the other hand' introduces a contrasting perspective. on the other hand引出對比觀點。"},
    {q:"If a question asks for the 'main purpose', you should identify:",o:["A minor detail","Why the author wrote the text","The most interesting word","The first sentence"],a:1,d:"easy",e:"Main purpose = author's reason for writing. 寫作目的。"},
    {q:"'Studies show that...' suggests the information is:",o:["Made up by the author","Based on research","An opinion","A joke"],a:1,d:"medium",e:"'Studies show' indicates research-based evidence. 基於研究證據。"},
    {q:"Which would be the best title for a passage about how penguins survive in Antarctica?",o:["Penguins: Masters of the Cold","Antarctica is Cold","Birds Can Fly","Fish in the Ocean"],a:0,d:"easy",e:"Best title captures main topic and focus. 最佳標題涵蓋主題和重點。"}
];