// ==========================================
// ICAS 科學題庫 - 100題
// ==========================================
const scienceQuestions = [
    // 物理 (30題)
    {q:"水在什麼溫度下沸騰？",o:["90°C","100°C","110°C","120°C"],a:1,d:"easy",e:"在標準大氣壓下，水的沸點是100°C。At standard pressure, water boils at 100°C."},
    {q:"聲音在什麼介質中傳播最快？",o:["空氣","水","固體","真空"],a:2,d:"medium",e:"聲音在固體中傳播最快，因為分子排列緊密。Sound travels fastest in solids."},
    {q:"磁鐵哪個部位磁力最強？",o:["中間","兩極","側面","底部"],a:1,d:"easy",e:"磁鐵的兩極（N極和S極）磁力最強。The poles have the strongest magnetic field."},
    {q:"彩虹有幾種顏色？",o:["5","6","7","8"],a:2,d:"easy",e:"彩虹有7種顏色：紅橙黃綠藍靛紫。A rainbow has 7 colors: ROY G BIV."},
    {q:"電流的單位是什麼？",o:["伏特","安培","歐姆","瓦特"],a:1,d:"medium",e:"電流單位是安培(A)，伏特是電壓，歐姆是電阻。Current is measured in Amperes (A)."},
    {q:"光在真空中的速度約是多少？",o:["300,000 km/s","150,000 km/s","1,000 km/s","30,000 km/s"],a:0,d:"medium",e:"光速約為300,000 km/s，是宇宙中最快速度。Speed of light ≈ 300,000 km/s."},
    {q:"物體自由落下時，速度會：",o:["不變","越來越慢","越來越快","先快後慢"],a:2,d:"medium",e:"由於重力加速度，速度會越來越快（每秒增加約9.8m/s）。Speed increases due to gravity."},
    {q:"哪種顏色吸收最多熱量？",o:["白色","銀色","黑色","黃色"],a:2,d:"medium",e:"黑色吸收所有色光，所以吸收最多熱量。Black absorbs all light colors."},
    {q:"電路中開關的作用是什麼？",o:["增加電壓","控制電流通斷","減少電阻","儲存電能"],a:1,d:"easy",e:"開關用於打開或關閉電路，控制電流。A switch controls current flow."},
    {q:"凸透鏡對光線的作用是什麼？",o:["發散","會聚","反射","吸收"],a:1,d:"medium",e:"凸透鏡將平行光線會聚到焦點。Convex lens converges light rays."},
    {q:"筷子在水中看起來彎曲是什麼現象？",o:["反射","折射","散射","繞射"],a:1,d:"medium",e:"光從空氣進入水時折射，使物體看起來位置偏移。Light bends (refracts) when entering water."},
    {q:"物體在月球上的重量與地球相比：",o:["相同","較重","較輕（約1/6）","沒有重量"],a:2,d:"medium",e:"月球重力約為地球的1/6，所以重量較輕。Moon's gravity is about 1/6 of Earth's."},
    {q:"摩擦力的方向通常是：",o:["與運動方向相同","與運動方向相反","垂直於運動方向","與運動無關"],a:1,d:"medium",e:"摩擦力總是與運動方向相反，阻止運動。Friction opposes motion."},
    {q:"下列哪種是化石燃料？",o:["太陽能","風能","煤炭","水能"],a:2,d:"easy",e:"煤炭是化石燃料。太陽能、風能、水能是可再生能源。Coal is a fossil fuel."},
    {q:"誰發現了槓桿原理？",o:["牛頓","阿基米德","愛因斯坦","伽利略"],a:1,d:"hard",e:"阿基米德發現槓桿原理。Archimedes discovered the lever principle."},
    {q:"簡單機械中的滑輪可以：",o:["改變力的方向","減少摩擦力","增加重力","產生電力"],a:0,d:"medium",e:"定滑輪可以改變力的方向，動滑輪可以省力。Pulleys change direction of force or provide mechanical advantage."},
    {q:"靜電現象中，同種電荷會：",o:["互相吸引","互相排斥","沒有作用","變成電流"],a:1,d:"medium",e:"同種電荷相斥，異種電荷相吸。Like charges repel, opposite charges attract."},
    {q:"凹透鏡對光線有什麼作用？",o:["會聚","發散","反射","吸收"],a:1,d:"medium",e:"凹透鏡使光線發散。Concave lens diverges light rays."},
    {q:"電壓的單位是什麼？",o:["安培","伏特","瓦特","歐姆"],a:1,d:"easy",e:"電壓單位是伏特(V)。Voltage is measured in Volts (V)."},
    {q:"牛頓第一定律又稱為什麼？",o:["萬有引力定律","慣性定律","作用力與反作用力定律","能量守恆定律"],a:1,d:"medium",e:"牛頓第一定律：物體保持靜止或等速運動，除非受到外力。Newton's First Law is the Law of Inertia."},
    {q:"溫度計是利用什麼原理製成的？",o:["熱脹冷縮","電磁感應","光的反射","壓強變化"],a:0,d:"easy",e:"溫度計利用液體熱脹冷縮的原理。Thermometers use thermal expansion."},
    {q:"聲音不能在什麼中傳播？",o:["空氣","水","固體","真空"],a:3,d:"easy",e:"聲音需要介質傳播，真空中沒有介質。Sound cannot travel in a vacuum."},
    {q:"杠桿的三個要素是：",o:["支點、施力點、抗力點","起點、終點、中點","上面、下面、中間","左邊、右邊、中間"],a:0,d:"medium",e:"杠桿三要素：支點（fulcrum）、施力點（effort）、抗力點（load）。Lever has fulcrum, effort, and load."},
    {q:"電阻的單位是什麼？",o:["安培","伏特","歐姆","瓦特"],a:2,d:"easy",e:"電阻單位是歐姆(Ω)。Resistance is measured in Ohms (Ω)."},
    {q:"平面鏡成像的特點是：",o:["倒立放大","正立等大","倒立縮小","正立放大"],a:1,d:"medium",e:"平面鏡成正立、等大、虛像。Plane mirrors produce upright, same-size virtual images."},
    {q:"浮力的大小與什麼有關？",o:["物體重量","液體密度","物體顏色","物體形狀"],a:1,d:"medium",e:"根據阿基米德原理，浮力等於排開液體的重量，與液體密度有關。Buoyancy depends on fluid density (Archimedes' principle)."},
    {q:"導體和絕緣體的區別是：",o:["導體容易導電","絕緣體比較重","導體比較硬","絕緣體比較貴"],a:0,d:"easy",e:"導體容易讓電流通過，絕緣體不容易。Conductors allow electricity to flow; insulators resist it."},
    {q:"冬天脫毛衣時產生火花是什麼現象？",o:["電流","靜電放電","短路","漏電"],a:1,d:"medium",e:"這是靜電放電現象。Static electricity discharge causes sparks."},
    {q:"功率的單位是什麼？",o:["安培","伏特","瓦特","焦耳"],a:2,d:"easy",e:"功率單位是瓦特(W)。Power is measured in Watts (W)."},
    {q:"電路短路會導致：",o:["電流過大","電流過小","電壓升高","電阻增加"],a:0,d:"medium",e:"短路時電阻極小，電流會變得很大，可能導致危險。Short circuits cause dangerously high current."},

    // 化學 (25題)
    {q:"水的化學式是什麼？",o:["CO₂","H₂O","O₂","NaCl"],a:1,d:"easy",e:"水的化學式是H₂O，由2個氫原子和1個氧原子組成。Water is H₂O."},
    {q:"下列哪種物質是酸性的？",o:["肥皂水","檸檬汁","漂白水","海水"],a:1,d:"easy",e:"檸檬汁含有檸檬酸，pH值小於7，呈酸性。Lemon juice is acidic (pH < 7)."},
    {q:"鐵生鏽是什麼類型的變化？",o:["物理變化","化學變化","生物變化","核變化"],a:1,d:"medium",e:"鐵生鏽是鐵與氧氣、水反應生成氧化鐵，是化學變化。Rusting is a chemical change."},
    {q:"哪種氣體佔地球大氣層比例最高？",o:["氧氣","二氧化碳","氮氣","氫氣"],a:2,d:"medium",e:"氮氣(N₂)約佔78%，氧氣約21%。Nitrogen makes up about 78% of atmosphere."},
    {q:"光合作用會釋放什麼氣體？",o:["二氧化碳","氧氣","氮氣","氫氣"],a:1,d:"easy",e:"光合作用吸收CO₂，產生氧氣和葡萄糖。Photosynthesis releases oxygen."},
    {q:"下列哪種是混合物？",o:["純水","食鹽","空氣","蒸餾水"],a:2,d:"medium",e:"空氣是氮氣、氧氣、二氧化碳等氣體的混合物。Air is a mixture of gases."},
    {q:"pH值為7表示物質是：",o:["酸性","鹼性","中性","強酸"],a:2,d:"easy",e:"pH 7為中性（如純水），小於7為酸性，大於7為鹼性。pH 7 is neutral."},
    {q:"哪種過程是吸熱反應？",o:["燃燒","冰塊融化","生鏽","爆炸"],a:1,d:"medium",e:"冰塊融化需要從環境吸收熱量。Melting ice absorbs heat (endothermic)."},
    {q:"鑽石和金剛石是同一種物質嗎？",o:["不是","是，都是純碳","不是，鑽石是石頭","是，都是金屬"],a:1,d:"medium",e:"都是純碳(C)的同素異形體，只是原子排列不同。Both are pure carbon (allotropes)."},
    {q:"防腐劑的主要作用是：",o:["增加營養","延長保質期","改變顏色","增加水分"],a:1,d:"easy",e:"防腐劑抑制細菌生長，延長食物保質期。Preservatives extend shelf life."},
    {q:"鹽酸(HCl)是酸性還是鹼性？",o:["酸性","鹼性","中性","視情況而定"],a:0,d:"easy",e:"鹽酸是強酸。Hydrochloric acid is a strong acid."},
    {q:"電解水會產生哪兩種氣體？",o:["氧氣和氮氣","氫氣和氧氣","二氧化碳和氧氣","氮氣和二氧化碳"],a:1,d:"medium",e:"電解水產生氫氣(H₂)和氧氣(O₂)。Electrolysis of water produces hydrogen and oxygen."},
    {q:"下列哪種是金屬？",o:["碳","硫","鐵","氧"],a:2,d:"easy",e:"鐵是金屬，碳和硫是非金屬，氧是氣體。Iron is a metal."},
    {q:"化學反應中，催化劑的作用是：",o:["改變反應顏色","加快反應速率但本身不變","增加產物重量","減少反應物"],a:1,d:"medium",e:"催化劑加快反應速率，但反應前後本身不變。Catalysts speed up reactions without being consumed."},
    {q:"食醋的主要成分是什麼？",o:["鹽酸","硫酸","醋酸","硝酸"],a:2,d:"medium",e:"食醋含醋酸（乙酸）。Vinegar contains acetic acid."},
    {q:"乾冰是什麼物質的固態？",o:["水","二氧化碳","氧氣","氮氣"],a:1,d:"medium",e:"乾冰是固態二氧化碳。Dry ice is solid carbon dioxide."},
    {q:"下列哪種是化學變化？",o:["冰塊融化","紙張撕碎","鐵生鏽","糖溶於水"],a:2,d:"easy",e:"鐵生鏽產生新物質（氧化鐵）。Rusting produces new substances."},
    {q:"原子中最小的粒子是：",o:["質子","中子","電子","夸克"],a:3,d:"hard",e:"夸克是構成質子和中子的更基本粒子。Quarks are smaller than protons/neutrons."},
    {q:"燃燒需要哪三個條件？",o:["燃料、氧氣、達到燃點","燃料、水、空氣","氧氣、氮氣、熱","燃料、電、水"],a:0,d:"medium",e:"燃燒三要素：可燃物、助燃物（氧氣）、達到着火點。Fire needs fuel, oxygen, and heat."},
    {q:"小蘇打的化學名稱是：",o:["氯化鈉","碳酸氫鈉","硫酸鈉","硝酸鈉"],a:1,d:"hard",e:"小蘇打是碳酸氫鈉(NaHCO₃)。Baking soda is sodium bicarbonate."},
    {q:"酸雨的主要成分是什麼？",o:["硫酸和硝酸","醋酸","鹽酸","碳酸"],a:0,d:"medium",e:"酸雨主要含硫酸和硝酸，由二氧化硫和氮氧化物形成。Acid rain contains sulfuric and nitric acids."},
    {q:"下列哪種元素是惰性氣體？",o:["氧氣","氮氣","氫氣","氬氣"],a:3,d:"medium",e:"氬氣是惰性氣體，化學性質穩定。Argon is a noble (inert) gas."},
    {q:"肥皂去污的原理是：",o:["肥皂是酸","乳化作用","肥皂有劇毒","肥皂是高溫液體"],a:1,d:"hard",e:"肥皂分子一端親油一端親水，能乳化油脂。Soap emulsifies oils and dirt."},
    {q:"光合作用在哪裡發生？",o:["動物細胞","植物細胞的葉綠體","細菌","真菌"],a:1,d:"easy",e:"光合作用在植物細胞的葉綠體中進行。Photosynthesis occurs in chloroplasts."},

    // 生物 (30題)
    {q:"植物進行光合作用需要什麼？",o:["氧氣和二氧化碳","陽光、水和二氧化碳","氧氣和水","陽光和氧氣"],a:1,d:"easy",e:"光合作用需要陽光、水和二氧化碳。Photosynthesis needs sunlight, water, CO₂."},
    {q:"人體最大的器官是什麼？",o:["肝臟","大腦","皮膚","心臟"],a:2,d:"easy",e:"皮膚是人體最大的器官。Skin is the body's largest organ."},
    {q:"哪種動物是哺乳動物？",o:["青蛙","企鵝","鯨魚","蜥蝪"],a:2,d:"easy",e:"鯨魚是哺乳動物。Whales are mammals."},
    {q:"細胞的「發電廠」是什麼細胞器？",o:["細胞核","粒線體","葉綠體","核糖體"],a:1,d:"medium",e:"粒線體負責細胞呼吸，產生ATP能量。Mitochondria are the 'powerhouses' of cells."},
    {q:"DNA的全名是什麼？",o:["去氧核糖核酸","核糖核酸","氨基酸","蛋白質"],a:0,d:"medium",e:"DNA = Deoxyribonucleic Acid（去氧核糖核酸）。DNA carries genetic information."},
    {q:"哪種生物是分解者？",o:["草","兔子","真菌","老鷹"],a:2,d:"medium",e:"真菌分解死去的有機物。Fungi are decomposers."},
    {q:"人類有幾對染色體？",o:["22對","23對","24對","46對"],a:1,d:"medium",e:"人類有23對（46條）染色體。Humans have 23 pairs of chromosomes."},
    {q:"光合作用在哪個細胞器中進行？",o:["細胞核","粒線體","葉綠體","液泡"],a:2,d:"easy",e:"葉綠體含有葉綠素，進行光合作用。Photosynthesis occurs in chloroplasts."},
    {q:"哪種血型被稱為「萬能供血者」？",o:["A型","B型","AB型","O型"],a:3,d:"medium",e:"O型血可捐給任何血型（但只能接受O型）。Type O is the universal donor."},
    {q:"動物細胞和植物細胞的主要區別是：",o:["植物細胞有細胞核","植物細胞有細胞壁和葉綠體","動物細胞比較大","動物細胞有葉綠體"],a:1,d:"easy",e:"植物細胞有細胞壁、葉綠體和大液泡。Plant cells have cell walls and chloroplasts."},
    {q:"哪個器官屬於消化系統？",o:["心臟","肺","胃","腎臟"],a:2,d:"easy",e:"胃是消化系統的一部分。The stomach is part of the digestive system."},
    {q:"什麼是「自然選擇」？",o:["人類選擇寵物","適者生存，不適者被淘汰","選擇天然食物","保護自然環境"],a:1,d:"medium",e:"自然選擇是達爾文提出的演化機制。Natural selection: survival of the fittest."},
    {q:"細菌是什麼類型的生物？",o:["真核生物","原核生物","病毒","真菌"],a:1,d:"medium",e:"細菌是原核生物，沒有細胞核。Bacteria are prokaryotes."},
    {q:"哪個系統負責運輸氧氣和養分？",o:["呼吸系統","消化系統","循環系統","神經系統"],a:2,d:"easy",e:"循環系統透過血液運輸物質。The circulatory system transports materials."},
    {q:"疫苗的作用是什麼？",o:["直接殺死病毒","幫助免疫系統認識病原體","替代藥物治療","改變DNA"],a:1,d:"easy",e:"疫苗刺激免疫系統產生抗體。Vaccines help the immune system recognize pathogens."},
    {q:"光合作用的產物是什麼？",o:["二氧化碳和水","葡萄糖和氧氣","氮氣和氧氣","葡萄糖和二氧化碳"],a:1,d:"easy",e:"光合作用產生葡萄糖和氧氣。Products of photosynthesis: glucose and oxygen."},
    {q:"人體有多少塊骨頭？",o:["106","206","306","406"],a:1,d:"medium",e:"成年人體有206塊骨頭。Adults have 206 bones."},
    {q:"紅血球的主要功能是：",o:["抵抗病菌","運輸氧氣","幫助消化","產生激素"],a:1,d:"easy",e:"紅血球含血紅素，運輸氧氣。Red blood cells transport oxygen."},
    {q:"下列哪種是無性生殖？",o:["受精","出芽生殖","交配","產卵"],a:1,d:"medium",e:"出芽生殖是無性生殖的一種。Budding is a form of asexual reproduction."},
    {q:"食物鏈中，生產者通常是：",o:["動物","植物","細菌","真菌"],a:1,d:"easy",e:"植物是生產者，能進行光合作用。Plants are producers (autotrophs)."},
    {q:"人體最大的淋巴器官是：",o:["肝臟","脾臟","胰臟","腎上腺"],a:1,d:"hard",e:"脾臟是最大的淋巴器官。The spleen is the largest lymphatic organ."},
    {q:"下列哪種是冷血動物？",o:["狗","貓","蛇","鳥"],a:2,d:"easy",e:"蛇是爬蟲類，屬於冷血動物。Snakes are cold-blooded (ectothermic)."},
    {q:"DNA複製發生在細胞週期的哪個階段？",o:["G1期","S期","G2期","M期"],a:1,d:"hard",e:"S期（合成期）進行DNA複製。DNA replicates during S phase."},
    {q:"下列哪種是遺傳性疾病？",o:["感冒","唐氏症","流感","肺炎"],a:1,d:"medium",e:"唐氏症是染色體異常導致的遺傳疾病。Down syndrome is a genetic condition."},
    {q:"生態系統中，消費者是指：",o:["植物","動物","細菌","真菌"],a:1,d:"easy",e:"動物是消費者，必須攝取其他生物。Animals are consumers (heterotrophs)."},
    {q:"人體的「化學工廠」是指：",o:["心臟","肝臟","肺","腎臟"],a:1,d:"medium",e:"肝臟負責多種化學反應和解毒。The liver performs many chemical functions."},
    {q:"下列哪種是哺乳動物的特徵？",o:["卵生","冷血","哺乳","鱗片"],a:2,d:"easy",e:"哺乳動物特徵包括哺乳餵養幼崽。Mammals nurse their young with milk."},
    {q:"光合作用中，光能被轉換成什麼？",o:["熱能","電能","化學能","動能"],a:2,d:"medium",e:"光能轉換成化學能儲存在葡萄糖中。Light energy → chemical energy in glucose."},

    // 地球科學 (15題)
    {q:"地球圍繞什麼運行？",o:["月球","太陽","火星","銀河系中心"],a:1,d:"easy",e:"地球圍繞太陽運行，公轉一周約365天。Earth orbits the Sun."},
    {q:"哪種岩石由火山熔岩冷卻形成？",o:["沉積岩","火成岩","變質岩","化石"],a:1,d:"easy",e:"火成岩由熔融岩漿冷卻形成。Igneous rocks form from cooled magma/lava."},
    {q:"潮汐主要由什麼引起？",o:["風","月球引力","太陽熱","地震"],a:1,d:"medium",e:"潮汐主要由月球（和太陽）引力引起。Tides are caused by the Moon's gravity."},
    {q:"哪種天氣現象與冷鋒有關？",o:["晴朗","雷暴","大霧","無風"],a:1,d:"medium",e:"冷鋒常帶來雷暴和降雨。Cold fronts often bring thunderstorms."},
    {q:"水循環中，水從地表回到大氣的主要過程是：",o:["降雨","凝結","蒸發","滲透"],a:2,d:"easy",e:"蒸發是水從液態變為氣態回到大氣。Evaporation returns water to the atmosphere."},
    {q:"哪種是可再生能源？",o:["煤炭","石油","太陽能","天然氣"],a:2,d:"easy",e:"太陽能是可再生能源。Solar energy is renewable."},
    {q:"臭氧層的主要功能是：",o:["產生氧氣","吸收紫外線","調節氣溫","阻擋隕石"],a:1,d:"medium",e:"臭氧層吸收有害紫外線。Ozone layer absorbs harmful UV radiation."},
    {q:"下列哪個是化石燃料？",o:["風能","地熱能","天然氣","潮汐能"],a:2,d:"easy",e:"天然氣是化石燃料。Natural gas is a fossil fuel."},
    {q:"地球內部結構從外到內依次是：",o:["地核、地幔、地殻","地殻、地幔、地核","地幔、地核、地殻","地殻、地核、地幔"],a:1,d:"medium",e:"結構：地殻→地幔→地核。Structure: crust → mantle → core."},
    {q:"哪種現象與全球暖化有關？",o:["冰川融化","海平面上升","極端天氣增加","以上皆是"],a:3,d:"easy",e:"全球暖化導致多種環境變化。All are effects of global warming."},
    {q:"地震的震央是指：",o:["地下岩層斷裂處","地面上震動最大的點","地震儀位置","海嘯發生地點"],a:1,d:"medium",e:"震央是地震波到達地表的投影點。Epicenter is the point on Earth's surface above the focus."},
    {q:"下列哪種雲層通常帶來降雨？",o:["卷雲","高積雲","雨層雲","卷積雲"],a:2,d:"hard",e:"雨層雲（Nimbostratus）是厚而灰暗的降雨雲。Nimbostratus clouds bring rain."},
    {q:"風的形成主要是由於：",o:["地球自轉","氣壓差異","地形起伏","海洋流動"],a:1,d:"medium",e:"風從高氣壓吹向低氣壓。Wind blows from high to low pressure areas."},
    {q:"下列哪種土壤最適合種植農作物？",o:["砂土","黏土","壤土","礫石"],a:2,d:"medium",e:"壤土（Loam）含有適量的砂、粉砂和黏土。Loam is best for growing crops."},
    {q:"日食發生時，哪個天體在中間？",o:["地球","太陽","月球","火星"],a:2,d:"medium",e:"日食時月球在地球和太陽之間。During a solar eclipse, the Moon is between Earth and Sun."}
];